### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by grimen** [pluginaweek/state_machine#105]
Highly recommended to keep track of comaptability among different setups. Takes < 5 min with basic setup, and with custom Gemfiles can be tested with multiple Rails versions smoothly. See: http://about.travis-ci.org/docs/user/build-configuration/

**Comment by obrie** [comment]
Definitely on my TODO list for this weekend :)

**Comment by obrie** [comment]
With the inclusion of the appraisal gem and integrating travis-ci, all of the different integrations should be automatically tested.  Thanks for filing this issue!
