### ISSUE TITLE
StateMachine::InvalidTransition: Cannot transition attendance via :mark_as_not_played from :na

### ISSUE THREAD

**Issue by ychaker** [pluginaweek/state_machine#109]
here's the code that i have:

``` ruby
class GuestListRsvpObserver < ActiveRecord::Observer
  def after_find(rsvp)
    # update the attendance if the event has passed
    if rsvp.na? && rsvp.guest_list.event.is_passed?
      case rsvp.status
      when GuestListRsvp::STATUS_NO, GuestListRsvp::STATUS_MAYBE, GuestListRsvp::STATUS_UNKNOWN
        rsvp.mark_as_not_played!
      when GuestListRsvp::STATUS_YES
        rsvp.mark_as_played!
      end
    end
  end
end

class GuestListRsvp < ActiveRecord::Base
  state_machine :attendance, :initial => :na do
    event :mark_as_played do
      transition all => :played
    end

    event :mark_as_not_played do
      transition all => :not_played
    end

    event :mark_as_no_show do
      transition :played => :no_show
    end

    state :na
    state :played
    state :not_played
    state :no_show
  end
end
```

obviously there is more to the code than what's above, but that's the relevant part.
the idea is to update the attendance state automatically if appropriate after the find.

im running locally:
Rails 3.0.7
ruby 1.9.2
gem 1.8.1
state_machine (1.0.1)
mysql

and locally it works just fine. on heroku on the other hand, i get the error:

StateMachine::InvalidTransition: Cannot transition attendance via :mark_as_not_played from :na

which actually should be an allowed state since i specified 'all' in the transition definition. i have other state machines that work fine, and other automatic updates similar to this that work too. am i missing something?

thanks for the help!

**Comment by ychaker** [comment]
i think it's also worth mentioning that the problem occurs with objects that existed before adding the attendance column which defaults to 'na'. 
but it's still a heroku issue only, locally old rsvps don't raise an exception.

**Comment by obrie** [comment]
Hey there -

Thanks for reporting this.  There's no reason the behavior should be different on one system vs. another.  What I'd recommend is that you change your `after_find` hook to log information as to why the error occurred.  The StateMachine::InvalidTransition exception can get raised for multiple reasons:
- The transition may not exist for the current state
- Validations may be failing on the record
- before_validation/transition/save/etc. hooks may be returning false, therefore cancelling the action

To debug, I'd change your `GuestListRsvpObserver` to the following:

``` ruby
def after_find(rsvp)
  # update the attendance if the event has passed
  if rsvp.na? && rsvp.guest_list.event.is_passed?
    begin
      case rsvp.status
      when GuestListRsvp::STATUS_NO, GuestListRsvp::STATUS_MAYBE, GuestListRsvp::STATUS_UNKNOWN
        rsvp.mark_as_not_played
      when GuestListRsvp::STATUS_YES
        rsvp.mark_as_played!
      end
    rescue StateMachine::InvalidTransition => ex
      logger.info ex.object.inspect
      logger.info ex.object.errors.to_a.inspect
      raise
    end
  end
end
```

Let me know if this helps!

Best,
Aaron

**Comment by ychaker** [comment]
Hi,
thanks for your reply, i've put that code in and will keep it. but i can no longer reproduce the error. which is a good thing, but i won't find out what the original problem was. i had to manually delete all the old RSVPs to be able to continue working and so that the rest of my team can test the features and stuff... so now i won't be able to have a similar situation again.

Thanks anyway for your help and if something else comes up i'll let you know... keep up the good work

**Comment by gauravk13** [comment]
thanks @obrie 
helps a lot
