### ISSUE TITLE
Confusing example in README

### ISSUE THREAD

**Issue by NeutralAngel** [pluginaweek/state_machine#113]
There are two things about the Vehicle example in the README that confused me.

1) There is no speed method defined for state :third_gear, so calling vehicle.speed when the vehicle object is in the :third_gear state causes a "NoMethodError: super: no superclass method 'speed'" to be thrown.

2) The auto_shop_busy? method always returns false, so I would assume that I could always repair my vehicle. However, you only transition from :stalled to :parked IF the auto shop is busy. I would think the code would be:

``` ruby
transition :stalled => :parked, :unless => :auto_shop_busy?
transition :stalled => same
```

**Comment by obrie** [comment]
Thank you for bringing this confusion to my attention!
