### ISSUE TITLE
RDoc framed formatting is all screwed up

### ISSUE THREAD

**Issue by jaylevitt** [pluginaweek/state_machine#115]
Code is mixed in with the text, lines of code are showing up as section headers, etc..

http://rdoc.info/github/pluginaweek/state_machine/master/frames

**Comment by obrie** [comment]
Thanks for pointing this one out.  I'll look into whether there's a way to provide different formatting to both GitHub and rdoc.info.

**Comment by obrie** [comment]
Looks like the yard folks _just_ added support for this, so it should get updated on the rdoc.info servers fairly soon.
