### ISSUE TITLE
Initial-state callback docs, use case could be improved

### ISSUE THREAD

**Issue by jaylevitt** [pluginaweek/state_machine#117]
The docs for callbacks on the initial state suggest that you (a) use a before_save hook or (b) call the starting event yourself.  The logical choice is to do both, e.g.:

```
class Model < ActiveRecord::Base
  before_save :start

  state_machine :state, :initial => nil do
    event :start do
      transition all => :started
    end
  end
end
```

However, this results in an infinite recursion.

Easy fix: say "Don't do that."

Better fix: It'd be really nice if you could, somehow, do that; even a special `after_initialize` hook would be better than having to call the `start` event manually from the controller. 

Best fix: Couldn't you rework that `after_initialize` hook so it gets called when you set the initial state?

**Comment by obrie** [comment]
Thanks for the feedback!  I've updated the docs to provide all of the various techniques that can be used and corresponding examples.  I think one of these 3 solutions should be sufficient for hooking into the initial state change.  I would prefer to be consistent in how transition callbacks get defined (whether that's for the initial transition or not) than introduce a new callback that's specific to the initial state.

The consistency is the main reason I've historically been against an initial-state-specific callback.  The callback really doesn't end up providing much info until the record gets saved.  Even once it's hooked into that spot, the lack of an event or from state makes it inconsistent with all other callbacks and, I think, confusing to work with.

I prefer to design the state machine definition to meet the needs for an initial state callback.

Hope this helps!
