### ISSUE TITLE
[Feature] detailed error handling

### ISSUE THREAD

**Issue by jaylevitt** [pluginaweek/state_machine#121]
When an event can't fire, there's no way to find out why not; I have to manually debug the code by commenting out parts of the state machine until it starts working again.

It'd be nice if state_machine could provide some sort of `.errors` method that would detail whether the state transition failed because:
- No such transition is defined, period
- The transition has a `before_transition` callback that failed (and the name of the method that was called back, if any)
- Validations failed in the `save` action

Ideally, this would show up in the exception when `event!` is fired, or in an ActiveRecord `.errors` integration if plain `event` is fired.

**Comment by JohnGoodman** [comment]
+1

**Comment by obrie** [comment]
Hey guys -

Thanks for taking the time to make this suggestion!  state_machine actually already integrates with ActiveRecord for reporting errors when transitions can't occur.  See below:

``` ruby
class User < ActiveRecord::Base
  state_machine :state, :initial => :pending do
    before_transition :pending => :active, :do => lambda {|user| user.name != 'invalid'}

    event :activate do
      transition :pending => :active
    end

    event :deactivate do
      transition :active => :pending
    end

    state :active do
      validates_presence_of :name
    end
  end
end

u = User.new                # => #<User id: nil, name: nil, state: "pending">
u.save                      # => true
u                           # => #<User id: 1, name: nil, state: "pending">

# Invalid transitions set error on "state"
u.deactivate                # => false
u.errors                    # => #<OrderedHash {:state=>["Can't change state from pending via deactivate"]}>

# Validation errors show up as normal if transition is allowed
u.activate                  # => false
u.errors                    # => #<OrderedHash {:name=>["can't be blank"]}>

# before_transition failures / rollbacks don't change anything -- they instead
# rely on you adding errors in the callback
u.name = "invalid"          # => "invalid"
u.activate                  # => false
u.errors                    # => #<OrderedHash {}>

# If everything passes, true is returned
u.name = "valid"            # => "valid"
u.activate                  # => true

# Attribute-driven event transitions behave similarly
u.state_event = "activate"  # => "activate"
u.save                      # => false
u.errors                    # => #<OrderedHash {:state_event=>["cannot transition when active"]}>
```

In this example you'll notice a few things.  First, if a transition isn't allowed, it is always reported in the errors hash.  Second, if a validation fails, only those attributes that failed will have an error reported -- the `state` / `state_event` fields will not have any errors.  The lack of an error on the `state` / `state_event` field indicates that the transition was allowed.

Third, any failures in a `before_transition` callback or rollbacks won't cause an error to be reported (other than the event returning false).  This behavior mirrors ActiveRecord's behavior in that if a `before_save` callback returns false or a `before_save` / `after_save` callback rolls back, then `save` just returns false without reporting which callback failed.  If there are callbacks that you have which utilize this technique of canceling a transition, then the responsibility is placed on the callback to add an error to the `errors` collection (or somehow track the failure elsewhere).

If the problem you're seeing is that nothing is getting added to the `errors` collection when an invalid event is attempted, then that's probably a separate issue and I'd be happy to dig into that.  Feel free to re-open the issue if you think this is still unresolved.

Hope this helps!
