### ISSUE TITLE
after_failure callback data changes rolled back on transition failure

### ISSUE THREAD

**Issue by jcoppedge** [pluginaweek/state_machine#122]
Consider this state machine on Rails ActiveRecord object:

``` ruby
  state_machine :status, :initial => :pending, :use_transactions => false do
    state :pending
    state :completed

    before_transition :pending => :completed, :do => :dispatch
    after_failure :on => :process, :do => :save_dispatch_logs
    event :process do
      transition :pending => :completed
    end
  end
```

:dispatch accesses an external web service and is certainly possible to fail, and it does return false if a failure occurred.  In the :dispatch chain  I also attempt to save the communication with the web service in a separate logging data table - however those entries are rolled back even though they are saved to the database in :save_dispatch_logs.  It seems incorrect that the after_failure database updates would be rolled back - how else would you store details about the transaction to the database?

**Comment by obrie** [comment]
Hey @jcoppedge -

Thanks for the great question!  I added some documentation to explain how to do exactly what you're asking.  This basically comes down to ensuring that the model you're saving in the `save_dispatch_logs` callback is using a separate database connection.  This allows the transactional behavior of the machine's model from affecting the dispatch logs.

Hope this helps!
