### ISSUE TITLE
"Cannot draw the machine. `gem install ruby-graphviz` >= v0.9.0 and try again."

### ISSUE THREAD

**Issue by dpmccabe** [pluginaweek/state_machine#124]
I'm using:
state_machine (1.0.2 01ea7de)
graphviz 2.28.0 from http://www.graphviz.org/Download_macos.php
ruby-graphviz 1.0.0

When I run "rake state_machine:draw FILE=account.rb CLASS=Account" I get the error "Cannot draw the machine. `gem install ruby-graphviz` >= v0.9.0 and try again."

**Comment by obrie** [comment]
Thanks for taking the time to report this issue.  I've updated the latest on master to give you some more information as to why ruby-graphviz can't be loaded.  Can you try this and let me know if the error provides you better insight?

If you're still having troubles, can you provide some more info about how you're testing this?  Are you running this as a Rails rake task, or standalone in the state_machine project folder?  Which version of rails and are you using bundler?

One possibility could be that although you've installed ruby-graphviz, you're using bundler which doesn't have the dependency declared.

Hope this helps!

**Comment by dpmccabe** [comment]
I fixed it. I added "ruby-graphviz" to my Gemfile and ran "bundle install" and it worked.
