### ISSUE TITLE
after_transition callback never called with Rails 3, Mongoid

### ISSUE THREAD

**Issue by chabgood** [pluginaweek/state_machine#126]
I am not seeing anything happen within the after_transition block.  I also am not seeing the mongoid observer being executed.

**Comment by ngw** [comment]
Same problem here.

**Comment by MirkoCindric** [comment]
having the same issue but with active record

**Comment by obrie** [comment]
Hey guys -

Thanks for the heads up!  This should be fixed now for anyone using Mongoid 2.2.x.  If you're still seeing this problem on the latest master branch, let me know and post a failing test case.

Best,
Aaron
