### ISSUE TITLE
State not changes with Mongoid > 2.1.9

### ISSUE THREAD

**Issue by cheef** [pluginaweek/state_machine#128]
When I try to change state via event nothing happens.

```
class Venicle
  include Mongoid::Document
  state_machine :state, :initial => :draft do
    event :first do
     transition :draft => :first_state
    end

    event :second do
      transition :first_state => :second_state
    end
  end
end

v = Venicle.new # state is draft
v.first! # state is draft too!
v.second! # raises an exception 
```

Version 2.1.9 is the latest when state machine is working, but 2.1, 2.2 and 2.3 don't

**Comment by obrie** [comment]
Hey @cheef -

Can you try this again with the latest version of state_machine (1.0.3)?

Thanks!

**Comment by obrie** [comment]
This should be fixed in the latest version... I'll re-open this issue if there's a test case still failing here.
