### ISSUE TITLE
Specify RDoc link in gemspec

### ISSUE THREAD

**Issue by jamesbebbington** [pluginaweek/state_machine#129]
I noticed that the [RDoc link](http://api.pluginaweek.org/state_machine) at the [Ruby Toolbox](https://www.ruby-toolbox.com/projects/state_machine) is broken. [According to the author](http://twitter.com/#!/TheDeadSerious/status/124096454393466880) you can specify the RDoc link in the gemspec and Ruby Toolbox will pick it up.

**Comment by colszowka** [comment]
Actually, I think the link is stated wrongly on the web interface of rubygems.org. That's where it should be fixed.

**Comment by obrie** [comment]
Thanks for the heads up, guys!  @colszowka - I should have read your comment before filing a support ticket on ruby-toolbox :)

This is all set on rubygems.org... just waiting for the changes to propagate.

**Comment by colszowka** [comment]
@obrie The updates happen every 3 hours normally. I ran a manual update just to check if things work as they should, and voila :)

**Comment by obrie** [comment]
Sweet, thanks!
