### ISSUE TITLE
transition without save?

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#13]
**Aaron Gibralter** opened this issue

I&rsquo;ve encountered a few cases where I might want to call a transition without immediately saving the record.

For instance, on line 166 of user.rb (http://gist.github.com/16815) in one of my before_save callbacks, I want to transition to an "unverified" email. I don&rsquo;t want to save _in_ my before_save callback though... Also on lines 105 and 106 of user.rb, I want to make a few transitions at once. It seems wasteful to make 3 save calls in a row.

Anyway, does anyone have thoughts on this commit which adds the ability to call any event without saving? I do it by allowing events to be called with a "false" argument.

http://github.com/agibralter/state_machine/commit/c588b743763921ab9d60999cc2878d93544db492

P.S. I did encounter a few bugs in my UserObserver code as a result of this changeset...  As you can see in user_observer.rb (http://gist.github.com/16815), it is possible for my after_unverify callback to get called before the user has been saved...  as a result user doesn&rsquo;t have an id yet. I don&rsquo;t think this is a fault of my commit though, more a fault of my callback design.

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/3)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
This ability has now been added using the same syntax you proposed (e.g. vehicle.park(false)).

(from [307ac8ebd5ba06d2e8dd47e7bbf6242b3747f56a]) Re-design to be library-agnostic (define state machines on any Ruby class, with integration support for ActiveRecord and DataMapper) http://github.com/pluginaweek/state_machine/commit/307ac8ebd5ba06d2e8dd47e7bbf6242b3747f56a

**Comment by obrie** [comment]
**Aaron Gibralter** commented

Is the code after that commit stable? I merged back to the master branch but it breaks my code: seems that my initial states aren&rsquo;t being set anymore...

**Comment by obrie** [comment]
It _should_ be stable, but that doesn&rsquo;t mean I haven&rsquo;t missed something.  Much of the library was rewritten since the last release, so it needs to go through the rounds a bit.  I&rsquo;ve got two libraries (has_messages and has_emails) written against the latest state_machine library and they seem to be passing all of their tests fine.

If you could open a new ticket describing the issue and an example that demonstrates the problem, that might help shed some light.  Thanks.

**Comment by nathanl** [comment]
If anyone stumbles across this issue, you might be interested in implicit state transitions: https://github.com/pluginaweek/state_machine#explicit-vs-implicit-event-transitions
