### ISSUE TITLE
Observer not firing for model with state_machine

### ISSUE THREAD

**Issue by MirkoCindric** [pluginaweek/state_machine#135]
Hi have a user model that fire the observer correctly but when l try it for another model that also implements state_machine not luck cant get any of the methods like after_transition or even after_create to fire in the observer just wont run it at all and yes l have it in the application.rb file

I am using rails 3.0.10 + mysql2 + state_machine and delayed_job

**Comment by obrie** [comment]
Hi there -

Thanks for taking the time to report this.  A few questions....
- Does your User model have a state_machine and fire observer callbacks correctly?
- If you remove state_machine from your other model, does it fire after_create callbacks correctly?
- Can you try using the latest version of state_machine on master?  There was a change I made to how observer callbacks get called which I haven't tagged a new release for yet.
- Can you provide a working example of this error?  I'm not able to reproduce locally and it would be great if I could get an example that I could debug with.

**Comment by MirkoCindric** [comment]
Hi obrie,

Finally got it working was and issue with the version of state_machine was using the 2nd latest version, tried the latest and was working but still very strange as to why as no real indication as to what the issue was
