### ISSUE TITLE
Are transition callbacks supposed to fire when state changes on a regular save?

### ISSUE THREAD

**Issue by aaronchi** [pluginaweek/state_machine#137]
I have a model set up like this:

```
state_machine :state, :initial => :pending do
  event :complete do
    transition [:pending] => :unverified
  end
  event :verify do
    transition [:pending, :unverified] => :verified
  end
  after_transition [:pending, :unverified] => :verified do |listing, transition|
    listing.person.update_attribute(:member_type, :professional)
  end
end
```

Right now, the transition only fires if I call `listing.verify!` but not if I update the state directly. Is this the intended behavior or should the model be recording state changes when done through a regular update?

**Comment by obrie** [comment]
Hey @aaronchi -

Setting the state directly bypasses state_machine altogether, so it will not fire any callbacks when this is done.  You could consider using the attribute-based event transitions which allow you to fire off an event when the machine's action ("save" in this case) is called.  For example:

``` ruby
vehicle = Vehicle.first
vehicle.state_event = "park"
vehicle.save!
```

In that example, the "park" event will be run when the Vehicle record is saved.  This will run all of the relevant callbacks related to that event.

In the future, let's using the mailing list for general questions like this -- http://groups.google.com/group/pluginaweek-talk.

Thanks!
