### ISSUE TITLE
State machine fails when using symbol values

### ISSUE THREAD

**Issue by apneadiving** [pluginaweek/state_machine#145]
Hi,

Background:
Using Mongoid, Rails 3.0.10, state_machine 1.1.0, `status` field is Symbol.

Working with a legacy app, I'm implementing a state machine to clean up.
The code is stuffed with many `object.status == :foo` so I'd like the statuses to remain symbols.

This in mind, I added the following in the state_machine:

```
state :in_creation, :value => :in_creation
state :in_progress, :value => :in_progress
state :in_review,   :value => :in_review
state :completed,   :value => :completed
state :paused,      :value => :paused
state :canceled,    :value => :canceled
```

And in console:
     pry(#Groups::ClientsController)> @project.can_cancel? 
     => true 
     pry(#Groups::ClientsController)> @project.status
     => :in_creation
     pry(#Groups::ClientsController)> @project.cancel
     => false
     pry(#Groups::ClientsController)> @project.status
     => "in_creation"

It's annoying because:
- I can't go from one status to another
- Status is changed from symbol to text after fail  

So I commented the lines giving values to the statuses and it works:

```
pry(#<Groups::ClientsController>)> @project.status
=> "in_creation"
pry(#<Groups::ClientsController>)> @project.cancel
=> true
pry(#<Groups::ClientsController>)> @project.status
=> "canceled"
pry(#<Groups::ClientsController>)> @project.status
=> "canceled"
```

I deduce there is something wrong with the `:value` statement. Is it due to Mongoid?

Thanks in advance.

Benjamin

**Comment by apneadiving** [comment]
I dare asking because it would determine much of my planning: Do you think you could get rid of this bug before the end of next week?

I'm well conscious your achieved job is already great and I've no deadline to give you :)
I simply need the info to know what path I should follow :)

Thanks in advance for any answer.

Benjamin

**Comment by obrie** [comment]
Hi Benjamin -

I apologize I've been time-strapped recently.  My gut feeling is that this isn't a problem in state_machine, but instead a problem in Mongoid.  I suggest either digging into what's going on in Mongoid when the value gets written to and read from or implementing a workaround.  I won't be able to debug this myself until next week.

Best,
Aaron

**Comment by apneadiving** [comment]
Ok, I'll take a look at this track this week end. 

Thanks for your answer :)

**Comment by apneadiving** [comment]
Because of our urge to release, I finally did:

```
def status
  self[:status].to_s
end

def status=(value)
  self[:status] = value.to_sym
end
```

This does the job even if it remains a workaround.

**Comment by obrie** [comment]
Turns out this was indeed an issue with state_machine causing the field to be stored as a string instead of a symbol.  That issue should now be fixed.

Thanks for raising the issue!

**Comment by textmaster** [comment]
Hi,

I work with  apneadiving  and even though since the 1.1.1 this particular issue has been resolved and the work around with the setters and getters is no longer required.
There is still a background issue that is causing havoc in our project. The fact that through the state_machine, the values written to the db is of String format rather than Symbol format as expected.

This throws off mongoid queries for embedded documents.

Any idea on this ? Thx.

Alex
