### ISSUE TITLE
How to test transition callbacks?

### ISSUE THREAD

**Issue by apneadiving** [pluginaweek/state_machine#147]
Hi,

I'd like to know what's the cleanest way to test that transition callbacks are being triggered.

For instance, how would you test:

```
    before_transition :parked => any - :parked, :do => :put_on_seatbelt
```

Thanks,

Ben

**Comment by obrie** [comment]
Hi Ben,

I'd be happy to help but this isn't the best place for it.  Please use the Google Group (https://groups.google.com/forum/#!forum/pluginaweek-talk) for your questions.

Best,
Aaron

**Comment by apneadiving** [comment]
Hi Aaron,

No problem :)

Ben
