### ISSUE TITLE
strange behavior

### ISSUE THREAD

**Issue by releu** [pluginaweek/state_machine#148]
Hi!

I've got a model with state machine:

``` ruby
state_machine :state, :initial => :real do
  state :real
  state :completed

  event :complete do
    transition :real => :completed, :if => :completable?
  end

  after_transition :real => :completed, :do => :ship
end
```

In 99.5% cases `complete` works. But for other method `ship` don't starts, but the record state updates to `completed`. 
I can't catch it in dev env. I debug each line to log file in production. Sometimes method `ship` called (most), sometimes don't.

I don't understand how it is possible. Do you have any ideas?

Rails 3.1.1, StateMachine 1.1.0, Ruby 1.9.3

**Comment by obrie** [comment]
Hi releu,

You're right, this doesn't seem possible.  If that's the entirety of your state machine definition and, each time, you're calling the `complete` method to create the transition, then there's no reason `ship` would ever get skipped unless the transition itself failed.  Have you validated that the transition itself isn't failing?

The only other alternative is that `ship` is being redefined elsewhere.  As a result, any debugging statements wouldn't show up.

I'd start with those 2 and see if you can figure anything out from there.
