### ISSUE TITLE
Inconsistent events error when all declared events are symbols (and states are integers)

### ISSUE THREAD

**Issue by cassiomarques** [pluginaweek/state_machine#154]
I have something similar to this state machine. This Status::FOO constants are integers.

``` ruby
state_machine :status, :initial => :begin do
  state :begin, :value => Status::BEGIN 
  state :assigned, :value => Status::ASSIGNED 
  state :revised, :value => Status::REVISED 
  state :documents_retrieval, :value => Status::DOCUMENTS_RETRIEVAL
  state :finished, :value => Status::FINISHED

  event :assign do
    transition :begin => :assigned
  end

  event :revise do
    transition :assigned => :revised
  end

  event :associate_to_unit do
    transition :revised => :documents_retrieval
  end

  event :finish do
    transition :documents_retrieval => :finished
  end
end
```

It was working fine with state_machine 1.0.2, but on 1.1.1 it's giving me the following error: :revise event defined as Symbol, "Designar" defined as String; all events must be consistent

(note that I have an i18n file where I translate the :assign event to "Designar".

Any ideas of what can br wrong?

Thanks!

**Comment by obrie** [comment]
Hey @cassiomarques -

Thanks for taking the time to report this issue!  In the latest revision, there was a change added to protect against the definition of states / events whose names are of different types (e.g. symbols vs. strings).  It looks like in your definition all events are defined as symbols, so there's nothing obvious in that code snippet that stands out as being a problem.

Can you expand a little bit when you say you have an i18n file where you translate the :assign event to "Designar"?  Are you saying you're actually changing attributes on internal state_machine definitions?  Or are you using state_machine's i18n support for defining the human-readable names for events?  Just for clarity, I'm referring to the documentation at http://rubydoc.info/github/pluginaweek/state_machine/master/StateMachine/Integrations/ActiveRecord under the "Internationalization" heading.

**Comment by cassiomarques** [comment]
Hum, I think I've found the origin of the problem! Because I need to generate the graphical version of my state machine with graphviz and I need all text in the image to be translated, I monkey-patched the following in a initializer:

(this machine.owner_class.enumerations[:status].t(name) code is mine, don't worry about it :)

``` ruby

module StateMachine
  class State
    def description
      return name.inspect unless name      
      name.is_a?(Symbol) ? I18n.t("state_machine.#{machine.owner_class.name.underscore}.states.#{name}") : machine.owner_class.enumerations[:status].t(name)
    end
  end

  class Event
    def name
      I18n.t("state_machine.#{machine.owner_class.name.underscore}.events.#{@name}")
    end
  end
end
```

So it looks like this is the cause of the error. Can you please tell me how can I achieve the same result with the new state_machine version, without breaking it?

My bad Aaron, sorry :(

**Comment by obrie** [comment]
Ah no worries, glad we found the issue.

To be honest, I don't know that there's a particularly good way to use the translated names in a graph without monkey-patching some of the internals even more.  However, I think being able to use the human name instead of the definition name is a valid thing to want to do.

I'd like to think about this one a little bit more and see what we can do about it.  I think it can be a built-in option that you just configure through the rake task.  Let me get back to you on this.

**Comment by cassiomarques** [comment]
Sure Aaron, thank you very much, sir!
