### ISSUE TITLE
Namespaced state machine

### ISSUE THREAD

**Issue by chikamichi** [pluginaweek/state_machine#156]
Hi,

I tried to use this feature, but the README provides weird information. In the `Vehicle` example, the state machine is called `alarm_state`, with a namespace `alarm`, but it then makes use of `#alarm_state`. I'd expected the state machine to be defined on `state`, not `alarm_state`.

Is there any extended example on this?

Thank you!

**Comment by obrie** [comment]
Hi @chikamichi -

Thanks for the question.  You're probably better off asking over on the mailing list with a question like this -- I prefer to use this forum for bug reports.  Onto the issue at hand...

When it comes to the `:namespace` option, all you're really doing is telling state_machine how to prefix / suffix the various state / event-related methods that it generates.  I think what's partially confusing you is how the attribute that stores the state value gets determined.  In all cases, the state attribute is always the same as the machine name -- that is, unless you override it with the :attribute field.  As an example:

``` ruby
state_machine :alarm_state, :attribute => :state, :namespace => 'alarm' do
  ...
end
```

In the README, we're telling state_machine to create a new machine called "alarm_state" that stores its values in an attribute also called "state" and that all of the generated state / event methods, which would normally _not_ have the name of the machine in it, be prefixed / suffixed with "alarm".  You could very well have used a namespace of "security" -- state_machine treats the configurations separately.

Hope this helps!

Best,
Aaron
