### ISSUE TITLE
Event named :duration doesn't seem to work?

### ISSUE THREAD

**Issue by ghost** [pluginaweek/state_machine#158]
I have the following state:     

state_machine :initial => :initial do
     state :initial do
        transition :to => :start_date, :on => :start_date
        transition :to => :start_time, :on => :start_time
        transition :to => :end_date, :on => :end_date
        transition :to => :end_time, :on => :end_time
        transition :to => :duration, :on => :duration
        transition :to => :start_day, :on => :start_day
        transition :to => :end_day, :on => :end_day
      end
     state :start_date
     end
     state ....
end

When an event is fired, e.g. :start_date, the sm does not transit to state :start_date. However, It does so when removing line "transition :to => :duration, :on => :duration" or changing the event name to something different than :duration, e.g. duration1.

**Comment by obrie** [comment]
Hey @MatthiasStumpp -

What version of state_machine are you running?  I'm not seeing this behavior on the latest released version (1.1.2).  See below:

``` ruby
class Vehicle
  state_machine :initial => :initial do
    state :initial do
      transition :to => :start_date, :on => :start_date
      transition :to => :start_time, :on => :start_time
      transition :to => :end_date, :on => :end_date
      transition :to => :end_time, :on => :end_time
      transition :to => :duration, :on => :duration
      transition :to => :start_day, :on => :start_day
      transition :to => :end_day, :on => :end_day
    end
  end
end

v = Vehicle.new   # => #<Vehicle:0xb71d0c60 @state="initial">
v.state           # => "initial"
v.start_date      # => true
v.state           # => "start_date"
v.start_date?     # => true

v = Vehicle.new   # => #<Vehicle:0xb71d0c60 @state="initial">
v.state           # => "initial"
v.duration        # => true
v.state           # => "duration"
v.duration?       # => true
```

This was tested on Ruby 1.8.7.  Do you have a simple example that's producing this behavior that I can run?  If you do, please let me know what version of state_machine and Ruby you're on.

I'm going to close this bug for now, but will re-open when we've got a reproducible case.
