### ISSUE TITLE
Add state descriptions?

### ISSUE THREAD

**Issue by bwlang** [pluginaweek/state_machine#161]
Wouldn't it be nice to have description on  states like this

state :parked, :description => 'the vehicle is not moving"

?

That would make it simpler to build a ui where some states need to be described in more detail.

Seems nicer than defining a description method for each state

brad

**Comment by obrie** [comment]
Hey @bwlang -

This is a good question.  I've actually addressed this in the past in a few different contexts.  See https://groups.google.com/forum/?hl=en#!topic/pluginaweek-talk/TTmzzISjAj8 and https://github.com/pluginaweek/state_machine/issues/24.

In all cases, my conclusion has basically been the same: I don't think this is state_machine's responsibility to track this information.  Here's a snippet of one of my responses:

"...the idea of how a state is represented is application-specific, be it an image, using an i18n library, etc. In addition, you may want to render a different human name [or description] on different pages or in different contexts. The use cases vary so widely that it begins to take the form of an application-specific implementation."

Of course, I'm open to feedback -- but, for now, I'd prefer to keep this responsibility outside of state_machine.
