### ISSUE TITLE
Rspec and state_machine

### ISSUE THREAD

**Issue by ghost** [pluginaweek/state_machine#163]
I have the following state machine

``` ruby
class Test < ActiveRecord::Base
  def end_call
    # Called twice
  end

  state_machine :state, :initial => :brand_new do
    after_transition :to => :end, :do => :end_call

    event :start do
      transition :start => :end
    end
  end
end
```

and the following test in rspec

``` ruby
it "should test the test" do
  Test = Factory(:test)
  test.start!
end
```

What happens is that end_call gets called twice. Do know its probably not an issue here. But googled everywhere and couldnt find an answer. Probably more people having the same problem as med out there.

**Comment by obrie** [comment]
Hi @popdevelop -

This will happen if you evaluate the class more than once.  Can you put a `puts` statement before your `Test` class and validate that you're only seeing the class evaluated once?

**Comment by popdevelop** [comment]
Yes you are correct the Class is evaluated twice. I guess I have to find out why. Thanks for helping me out.

**Comment by popdevelop** [comment]
Seems like my problem is that I am using spork and reloads the models every iteration however I am using ActiveSupport::Dependencies.clear to get rid of the dependencies for ActiveSupport can I do something equivalent for state_machine. Thanks for your support.

**Comment by popdevelop** [comment]
My question is, is there a way to remove the already loaded state_machine since I need to reload the Class without having the callback beeing triggered twice.

**Comment by obrie** [comment]
Ah, sorry I didn't realize you were asking a question in your previous comment.  There's no support way for clearing out the callbacks for a state machine.  You can certainly dig your way into the `StateMachine::Machine` instance, but I wouldn't recommend that.

I'd recommend taking a look at issue #67 where I've addressed this before.  You'll see near the end of that issue that the real problem had to do with how Spork was being configured for that particular user.  The conversation spilled over to here as well where a solution to the Spork issue was proposed and worked for everyone involved: https://github.com/mongoid/mongoid/issues/1752

**Comment by simmogs** [comment]
+1 I'm getting the same problem with and without spork.

**Comment by maxjustus** [comment]
me too :((

**Comment by dwilkie** [comment]
Hey @obrie I tried to look at your solution here: https://github.com/obrie/Issue-illustration/commit/aa9562011c5db4d4923de79942b8762fcebb1228

But it seems like you have removed that repo. Can you post your solution in this issue?

Cheers

**Comment by dwilkie** [comment]
To get this to work with Spork and RSpec I did the following:
Removed this line from my spec helper (which I added  to get spork to reload the classes on each run...)
`Dir[Rails.root.join("app/**/*.rb")].each { |f| load f }`

And following the guide here: http://my.rails-royce.org/2012/01/14/reloading-models-in-rails-3-1-when-usign-spork-and-cache_classes-true/ I added the following line to my Spork.prefork block _before_ this line `require File.expand_path("../../config/environment", __FILE__)`

```
  # Prevent main application to eager_load in the prefork block (do not load files in autoload_paths)
  require 'rails/application'
  Spork.trap_method(Rails::Application, :eager_load!)
```

Which enables spork to load the files on each run again

**Comment by semarco** [comment]
Thanks, this saved my day :-)))
