### ISSUE TITLE
Howto get all events from model class

### ISSUE THREAD

**Issue by ghost** [pluginaweek/state_machine#165]
Is it possible to get all events from a model class? I want to filter a list by events.

There was a [similar question on mailinglist](http://groups.google.com/group/pluginaweek-talk/browse_thread/thread/39e785cee0ba9309/cee2f2713f65c2ae) about all transitions.

**Comment by obrie** [comment]
Hi @tonymarschall -

Please use the mailing list for usage questions -- http://groups.google.com/group/pluginaweek-talk.

You can get all of the events defined for a model like so:

``` ruby
Vehicle.state_machine.events.map(&:name)
```

You can also get all of the possible events that can be run on an instance like so:

``` ruby
Vehicle.new.state_events
```

Hope this helps.
