### ISSUE TITLE
StateMachine::InvalidTransition raised inappropriately

### ISSUE THREAD

**Issue by rantler** [pluginaweek/state_machine#166]
When using an after_transition block to, for example, record auditing log records, an exception can occur that is extremely misleading. For example in the code below the `Auditor` record will be invalid because `:something` is nil.

``` Ruby
class Auditor < ActiveRecord::Base
  validates :something, :presence => true
  belongs_to :owner, :polymorphic => true
end

class AuditableThing < ActiveRecord::Base
  ...
  state_machine :state, :initial => :open do
    event :cancel do
      transition :open => :cancelled
    end
    ...
    after_transition :to => :cancelled do |record|
      Auditor.create!(:owner => record, :something => nil)
    end
  end
  ...
end

```

However, the exception raised is: `StateMachine::InvalidTransition: Cannot transition state via :cancel from :cancelled`

This is a misleading exception and can cause a great deal of time to be consuming tracking down the underlying cause. The actual error in this case is: `#<ActiveRecord::RecordInvalid: Record Invalid: Something cannot be blank>`

It seems as though it would be better if `StateMachine` could raise the underlying exception rather than its own in this case, since the transition is in fact valid, rather it is the `Auditor` record that is invalid.

_Please note, I have read the details of issue #138 and I believe that this is a related, but different issue._

**Comment by obrie** [comment]
Hey @rantler -

Thanks for bringing this issue up.  What you're seeing is actually a side effect of how Rails 3.2 (might also affect 3.0 / 3.1) handles raising ActiveRecord::RecordInvalid exceptions.  Let's look at an example:

``` ruby
class Campaign < ActiveRecord::Base
  has_one :creative

  after_save do
    creative.title = nil
    creative.save!
  end
end

class Creative < ActiveRecord::Base
  belongs_to :campaign, :inverse_of => :creative

  validates :title, :presence => true
end
```

In the above class definitions, the example is simple: when a campaign is saved, it'll attempt to cause the associated creative to raise an exception.  However take a look at the behavior of this:

``` ruby
campaign = Campaign.first # => #<Campaign id: 1, status: "draft">
#  Campaign Load (0.2ms)  SELECT "campaigns".* FROM "campaigns" LIMIT 1
campaign.save # => false
#  (0.1ms)  begin transaction
#  Creative Load (0.2ms)  SELECT "creatives".* FROM "creatives" WHERE "creatives"."campaign_id" = 1 LIMIT 1
#  (0.1ms)  rollback transaction
```

Notice no exception was raised.  This is a new behavior of Rails.  It won't raise the exception because the Campaign was valid -- it just rolls back the transaction and returns false.

With this context, you can now gain a better understanding for what's happening within state_machine.  When you attempt to run an event, it's going to call `save` on the record -- that's going to return false and, as a result, raise a StateMachine::InvalidTransition exception.  In fact, if you were to dig into the code, you'll find that state_machine never swallows exceptions or re-raises them as something different.  Exceptions (like if you were to raise an ArgumentError) will always pop up the stack so that you can properly rescue them.

Hope this helps explain things!

**Comment by rantler** [comment]
Thank you very much for the lucid explanation of transaction rollback behavior!

I must say, however, that I do not believe that our issue is caused by
this behavior. The issue is that the exception being raised in the
:after_transition block is that an invalid state transition is
occurring, when that is not actually the underlying problem.

In the example I posted in the issue on github, it is clear that the
exception being raised by ActiveRecord is indeed the RecordInvalid
exception, but this exception is apparently being hidden inside
StateMachine and instead an InvalidStateTransition exception is
raised.

This was all the more confusing because in our case, since the
exception message was "cannot transition to :cancelled via :cancel"
(or something to that effect), yet the exception was raised inside the
/after_transition/ block, where the model had /already/ transitioned
to that state!

If we ensure that our model is valid before saving it in the
after_transition block, then no InvalidStateTransition exception is
being raised.

To be clear, we're talking about two different models here, one that
is using StateMachine and another that is not and it is the model that
is /not/ using StateMachine that is invalid in this failure case.

On Wed, Mar 14, 2012 at 4:33 PM, Aaron Pfeifer
reply@reply.github.com
wrote:

**Comment by obrie** [comment]
Hey @rantler -

I think the part you're missing is that `after_transition` hooks in state_machine execute as part of ActiveRecord `around_save` hooks.  As a result, ActiveRecord is eating your `ActiveRecord::RecordInvalid` exception  -- not state_machine.  As well, ActiveRecord provides _zero_ information about that in the record's `errors` array.  There's no way to detect the fact that the association was invalid unless you personally add something to the record's `errors` array.

Here's actually what's happening under the hood:
1. You call `auditable_thing.cancel`
2. state_machine sets the `state_event` to "cancel"
3. state_machine calls `auditable_thing.save`
4. ActiveRecord call's state_machine's before_validation hook which reads from `state_event` and sets the state to "cancelled"
5. ActiveRecord call's state_machine's around_save hook which eventually executes your `after_transition` hook
6. ActiveRecord catches the `ActiveRecord::RecordInvalid` exception, swallows it, and returns `false`
7. state_machine (from step 2) gets `false` as the return value
8. state_machine attempts to see if there are any errors on the object and, if detected, indicates that information in the exception's message

There certainly are ways that you can force this to change such that `after_transition` hooks get executed outside of ActiveRecord's `around_save` hook, but I wouldn't want to go down this path.  You're eventually going to encounter the same problem I mentioned previously where you end up putting it in an `after_save` hook and the exception gets swallowed.

Hopefully this clears things up.  There are definitely no cases in state_machine where exceptions are getting swallowed and re-thrown as a different exception.

**Comment by rantler** [comment]
Ah. I understand now. Thanks again for taking the time to explain everything so clearly.
