### ISSUE TITLE
Unable to supply params when transitioning between states

### ISSUE THREAD

**Issue by mhuggins** [pluginaweek/state_machine#168]
It doesn't look like there's any way to supply a parameter when transitioning between states.  Let's say for example that we have a system where users submit something that needs to be reviewed, meaning there will be states `:pending`, `:approved`, and `:rejected`.

When this object transitions from `:pending` to `:rejected`, it would be nice to supply a simple string representing the reason it was rejected.  Ideally, this could be used in the `before_transaction`, `after_transaction`, etc.  For example, you may want a user to receive an email that their submission was not just rejected, but instead was rejected _because of XYZ_.

As far as I can see from the docs, this is not possible, unless I am missing something.

**Comment by obrie** [comment]
Hey @mhuggins -

I'd recommend using the mailing list in the future for a usage question like this -- http://groups.google.com/group/pluginaweek-talk

It actually is possible to do this currently :)  See the "Defining additional arguments" section at http://rdoc.info/github/pluginaweek/state_machine/master/StateMachine/Machine:event

**Comment by joshuapinter** [comment]
It is indeed already supported. For the sake of others landing here, here's what a simple example looks like: 

```ruby
after_transition on: :mark_as_rejected do |article, transition|
  reason = transition.args.first #=> "Title is too clickbaity."
  article.reject!( reason ) 
end
```

And then you would call it like this:

```ruby
article.mark_as_rejected( "Title is too clickbaity." )
```

Not super elegant or explicit but very flexible and powerful. Righteous.
