### ISSUE TITLE
errors/validation in callbacks, not persisting somehow?

### ISSUE THREAD

**Issue by brentkirby** [pluginaweek/state_machine#172]
Is it possible to invalidate a record within a before_transition callback? When transitioning to a new state (with :action save), I am running a method to perform a few tasks, and should those fail they add errors on the model.  In this case I'm posting data to an api.

``` ruby

state_machine :state, :initial => :pending, :action => :save_state do
  event :publish do
    transition [:pending] => :published
  end

  before_transition :pending => :published, :on => :publish :do => :publish_data_to_remote_service

  event :repost do
    transition [:ended] => :published
  end

  event :end do
    transition [:published] => :ended
  end
end

def publish_data_to_remote_service
  # performs action here, assigns results to 'result'
  if result
    # update some attributes on the model for saving
    return true
  else
    self.errors.add(:response, 'Error message from response')
    return false
  end
end

```

When running `model.publish` the callback runs, publish_date_to_remote_service is run, and that process works as expected. I've specced out the functionality (webmocking the api data so no connection actually happens). When successful, everything works fine, however, when unsuccessful, the model seems to lose all errors.

``` ruby
context 'when the request is un-successful' do

  before do
   # request is stubbed here
    listing.publish
  end

  it 'should not update the listing' do
    # makes sure no data was updated
    listid.should be_nil
  end

  it 'should invalidate the listing' do
    listing.should_not be_valid
  end

  it "should add the api error to the listing's 'response'" do
    listing.should have(1).errors_on(:response)
  end
end

```

I've tried setting up the before_transition a number of different ways, but the model always comes out valid, and all errors have been removed. I've also tried 

``` ruby

before_transition :pending => :published do |record, transition|
  unless record.publish_data_to_remote_service
    record.errors.add(:response, "Message from response")
    throw :halt  # also tried just returning false  here.
  end       
end

```

as well as other variations. So far the only way I can get the model to actually end up invalid, is to double check everything in another validation

``` ruby
validate :was_last_request_valid?


def publish_data_to_remote_service
  # performs action here
  if result
    # update some attributes on the model for saving
    return true
  else
    @error_response =  'Error message from response'
    return false
  end
end

def was_last_request_valid?
  return true unless @error_response
  self.errors.add(:response, @error_response)
  @error_response = nil
  false
end

```

I think I'm missing something here, but couldn't find anything in the docs or google group etc that seemed to help. The same results happen outside of rspec as well, so its definitely not related to the test env, and I can actually see the model as invalid when checking within the publish_data_to_remote_service method. I was also wondering if Rails' validations were maybe being run after the state machine callback and calling `errors.clear`? Not sure if thats the case or not.

Any help/advice would be awesome :) state_machine is perfect for this case, as the model is attached to an ebay listing, but I'm having trouble coming up with a clean solution to handle invalid state transitions based on the result of a request.

**Comment by obrie** [comment]
Thanks for reporting this!  I'll be taking a look at this Saturday the latest.

**Comment by brentkirby** [comment]
If it helps I think the issue is the order in which the callbacks are run. It seems like it runs before_transition prior to rails validations. Looks like when rails runs the validation, it does errors.clear, then validation callbacks, which means anything added in a before_transition simply gets cleared out. I'm not sure if the order could be changed easily, but maybe running  before_transition right after validations might do the trick. Then the before_save could be halted and the errors should persist.

**Comment by obrie** [comment]
Hey @brentkirby -

This is a great question.  For future reference, let's use the Google Group for questions like this.  I prefer to keep the Issues list primarily for bugs.  The issue you're running into here is that `listing.should have(1).errors_on(:response)` actually calls `valid?` on the object (even though state_machine itself has already performed some validations and added errors).  This is the incorrect behavior.  When you call `publish`, you should be looking at whatever errors are set on the object.  Re-running the validations makes no guarantees that you'll get the same errors.  See http://rspec.rubyforge.org/rspec-rails/1.1.11/classes/ActiveRecord/Base.src/M000013.html for the implementation of `errors_on`.

So in this case, what you should be doing is inspecting the `errors` array yourself and not relying on this rspec matcher.

Hope this helps!

Best,
Aaron

**Comment by brentkirby** [comment]
Yeah that sounds just like what I was seeing, though its related to rails clearing errors thats the issue, not rspec. In this case, since the behavior of `publish` is transitioning the model and saving it, rails will run validations and callbacks like normal. The issue is that since before_transition runs before validations, any errors added are wiped by rails. 

You're correct about the spec, though from a functional standpoint you'd actually want the model to be invalid. Since by default state_machine saves and thereby validates the model, even checking errors.empty? wouldn't work in most scenarios. 

[Heres the real issue](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations.rb#L176) from rails `valid?`  

I don't think its a bug really, more of a feature/change request. If its possible to run before_transition callbacks maybe  after_validation instead that could solve the issue?  Perhaps state_machine includes a validation method that runs before_transition callbacks, so that the chain could be halted at that point in time, as well as invalidating the model if desired. I'll see if I can find a few minutes to fork and write a couple specs/tests for the behavior.

**Comment by obrie** [comment]
I just want to make sure to clarify a few things.  If you call `publish` and you return false in a `before_transition` callback because you've added some errors, this actually cancels the transition before Rails ever has a chance to run validations.  As a result, even though `before_transition` runs before validations, Rails will never wipe the errors during that method call and you will have access to the errors that you added during the `before_transition` callbacks.

_However_, if you then decide to call `valid?` _after_ calling `publish`, this will definitely clear the errors which is what I'd expect it to do -- there's no guarantee that the same validations will display twice during subsequent validation invocations.

Given this understanding (which seems to conflict with statements in your first paragraph), do you think there's still a change needed?

**Comment by brentkirby** [comment]
Yeah we're definitely on the same page, I think the second part of what you were saying is what's hanging me up :)  I think it would be useful if there was no subsequent validation, ie if a before_transition invalidates a model its no different than any other validation. As a random example, say I have a document that a user can publish if desired.  They make a few changes, and "publish". Publishing involves some functionality that may or may not reject that event (and create an error on failure). Id expect the result of the publish transition to include that error as well as any other errors that may apply. Since publish performs a save of the model, I'm using it to actually perform the save, as well as run additional functionality from my before_transition callback. (kind of like an "event" so to speak)

``` ruby

class Document < ActiveRecord::Base
  validates :title, :presence => true

  state_machine :state, :initial => :pending do
    event :publish do
      transition [:pending] => :published
    end

    before_transition :pending => :published, :do => :perform_some_action
  end

  def perform_some_action
     # some action that fails
     self.errors.add(:state, "You can't publish this because I don't like it")
  end
end


doc = new Document(:body => 'some content')
doc.publish #=> false
doc.valid? #=> false
doc.errors # would have errors for both `state` and `title` since title was also missing

# likewise on updating

doc = new Document(:body => 'some content', :title => 'Title of doc')
doc.valid? #=> true
doc.save #=> true
doc.title = nil
doc.publish #=> false
doc.valid? #=> false
doc.errors # would have errors for both `state` and `title` since title was removed


```

I know you can have state based validations ie

``` ruby

state :pending do
  validate :perform_some_action
end

```

But that would run each time, whereas perform_some_action should really only run when someone tries to "publish" the document.  I may be missing something somewhere where that functionality can be done easily, if so I just couldn't figure it out without a few work-arounds. I may also be trying to use it in a way that isn't really intended, hence the possible feature request :)

**Comment by the8472** [comment]
This is a real issue since calls to `valid?`  can happen practically anywhere, even some 3rd party code.

I want to cause a `transition :some_state => same`  to fail if certain parameters are not passed in. Since valid? always clears all errors I cannot use rails validations to do this directly as they don't know about the failed transition, they can only validate things based on the current state.

My solution is
1. Have a `last_transition_errors` instance variable
2. Add a validation that simply merges the transition errors back into the regular errors
3. Clear last_transition_errors before a transition
4. Set last_transition_errors when a `before_transition` fails

This way one can inform the user (using rails' form error helpers) about the causes without having to worry about calls to valid? (which really can happen anywhere)
