### ISSUE TITLE
Conditional transition ignored when I use update_attributes

### ISSUE THREAD

**Issue by lucasas** [pluginaweek/state_machine#173]
Hi guys,

I've a project here using state_machine 1.1.2 and rails 3.2.1. I've some controllers, and these controllers receive into params, an attribute called state, like this: 

``` ruby
params[:my_model][:state] # parked
```

And I have this code:

``` ruby
class Vehicle
  include Mongoid::Document

  field :brand, :type => String

  validates_presence_of :brand

  state_machine :state, :initial => :parked do
    event :idle do
      transition :parked => :idling, :if => lambda { |vehicle| vehicle.valid? }
    end

    event :park do
      transition :idling => :parked
    end
  end
end
```

I try to create a vehicle:

``` ruby
v = Vehicle.create
puts v.state # parked
puts v.valid? # false
```

And of course, my model is invalid and its state is parked.

If I try change the state to idling, state_machine will consider my conditional transition

``` ruby
v.idle
puts v.state # parked
```

If I fix my model:

``` ruby
v.brand = "GM"
v.idle
puts v.state # idling
v.park
puts v.state # parked
```

Now, vehicle's state is parked, but was idling. If I put my model in an invalid state

``` ruby
v.brand = nil
```

And try update some attributes, that change my model to be invalid:

``` ruby
v.update_attributes :brand => nil, :state => "idling"
```

The state is changed to # idling

Is it possible, state_machine consider my conditional transition when I'm using update_attributes?

Thanks guys

**Comment by lucasas** [comment]
Someone can answer my question, please

**Comment by obrie** [comment]
I'll help out asap -- I'll definitely get to this Saturday the latest.

**Comment by obrie** [comment]
Hi @lucasas -

I would highly recommend _against_ checking for validation in a transition conditional (i.e. `:if`) and setting the `state` directly.  It is not possible for state_machine to check for valid transitions when you're changing the state directly.  When you're doing this, state_machine assumes that you want to basically go around the machine's definition and override any existing conditions for transitions.

If you want to accept new state transitions from the controller, I would highly recommend looking at the REST examples at https://github.com/pluginaweek/state_machine/tree/master/examples/rails-rest.

Hope this helps!

Best,
Aaron
