### ISSUE TITLE
Is it possible to send parameters to an event?

### ISSUE THREAD

**Issue by sporto** [pluginaweek/state_machine#179]
In many cases I will like to send parameters to an event e.g.

```
document.publish(current_user)
```

So I could decide wherever the event is valid or not or just trigger another action e.g. storing a log of who published the document

Is it possible to do this?

Thanks

**Comment by obrie** [comment]
Yes it is.  See the "Defining additional arguments" section here: http://rdoc.info/github/pluginaweek/state_machine/StateMachine/Machine:event

If you can, please use the Google Group in the future for questions like this -- https://groups.google.com/forum/?fromgroups#!forum/pluginaweek-talk

Hope this helps!
