### ISSUE TITLE
Cannot set states (properly) via forms

### ISSUE THREAD

**Issue by rathgar** [pluginaweek/state_machine#180]
I was hoping to be able to change states via a web form but for some reason even though the state is changed, no transition callbacks are called. Is this way of changing states supported?

In the forms I'm using to get the states it can go to (including the current state):

``` rails
  = f.select :state, @thingamy.state_paths.to_states | [@thingamy.state_name]
```

I realise that this will just result in the equivalent of a `@thingumy.state = params['state']` on the controller side but I thought that `state_machine` might override the `thingumy#state=` method in order to enable this behaviour. Perhaps this cannot be done.

Is there an accepted way or changing states via forms or is it necessary to handle it in the controller by catching the state and calling a state change method separately?

**Comment by obrie** [comment]
There is an accepted way of doing this.  Take a look at https://github.com/pluginaweek/state_machine/tree/master/examples/rails-rest and you should find everything you need.  If possible, it would make more sense to post a question like this to the Google Group in the future -- https://groups.google.com/forum/?fromgroups#!forum/pluginaweek-talk

Hope this helps!

**Comment by rathgar** [comment]
I thought there might be, just couldn't find it anywhere. Many thanks for the pointers.
