### ISSUE TITLE
Is there anyway to avoid save method execution after change state

### ISSUE THREAD

**Issue by macedo** [pluginaweek/state_machine#182]
it would be fantastic if had a way to avoid method save execution after change states. Is there?

**Comment by obrie** [comment]
Yes there is.  See the "Instance Methods" section documented at http://rdoc.info/github/pluginaweek/state_machine/StateMachine/Machine:event.  You'll notice it indicates that if you pass in `false` as the last argument to an event method that it'll skip the action associated with the machine (`save` in the case of using an ORM like ActiveRecord).

If possible, please use the Google Group for questions like this in the future -- https://groups.google.com/forum/?fromgroups#!forum/pluginaweek-talk

Hope this helps!
