### ISSUE TITLE
Find all by state?

### ISSUE THREAD

**Issue by pjammer** [pluginaweek/state_machine#186]
Maybe it's me, or my implementation of state_machine, but simply put can i 

"Find all records of a Model that have the state of :beginning."

All the examples are of a Single instance of a Class. I guess I want it on the whole class?

Thoughts?  I'll even take rtfm, as long as you point me to the section i missed.

My app needs to show all @user.shipments_by_state(:in_process).  Or find many instances of Shipment in a scope called in_process that uses things like `where(:state => 'in_route')` or something.

**Comment by obrie** [comment]
See the "Scopes" section at http://rdoc.info/github/pluginaweek/state_machine/StateMachine/Integrations/ActiveRecord.  If you can, it'd be great if you could use the Google Group for questions like this in the future -- https://groups.google.com/forum/?hl=en#!forum/pluginaweek-talk

Thanks and hope this helps!
