### ISSUE TITLE
Missing documentation for #state_event = 'event_name'

### ISSUE THREAD

**Issue by sfsekaran** [pluginaweek/state_machine#188]
I remember seeing documentation for this a long time ago. I needed it again recently, but it took me a while to dig up the unit test that outlined that functionality.

It would be useful to other devs to have it, yes? (Especially for submitting the next event from a form)

**Comment by sfsekaran** [comment]
I realize that it's in the rdocs now. Maybe it's a good thing to put in the README.md in the ActiveRecord section, too?

**Comment by obrie** [comment]
Agreed -- this should be improved.  Closing this in favor of tracking it in #225 since someone's opened a PR for it.
