### ISSUE TITLE
#state_path causes recursive loop

### ISSUE THREAD

**Issue by semarco** [pluginaweek/state_machine#189]
Hi,
# state_path works fine for simpler state_machine definitions, but comes up with an recursive loop with more realistic transition definitions ..

we have a state machine like this:

``` ruby
state_machine :state, :initial => :pending do

    state :pending
    state :open
    state :sold
    state :after_sales_sold
    state :unsold
    state :canceled
    state :rescheduled

    event :reset do
      transition :open => :pending
    end

    event :mark_sold do
      transition all => :sold
    end

    event :mark_unsold do
      transition all => :unsold
    end

    event :mark_after_sales_sold do
      transition all => :after_sales_sold
    end

    event :open do
      transition :pending => :open
    end

    event :reopen do
      transition [:canceled, :closed] => :open
    end

    event :close do
      transition :pending => :closed
    end

    event :cancel do
      transition [:pending, :open] => :canceled
    end

  end


# this results in very slow state_path calculation, and returns *280818* lines!!

 Report.new.state_paths.flatten.count
 => 280818 


```

maybe I missed something :-/

Thanks for you help!!

**Comment by peppyheppy** [comment]
I also have this issue. Its related to the use of 'all' and 'any'.

For example, the following will return the state_paths quickly:

``` ruby
event :start do
    transition :requested => :started
end
```

BUT, if we replace a specific "from state" with 'any' or 'all' it will loop more or less infinitely.

``` ruby
event :start do
    transition all => :started
end
```

Been looking into it for a bit and I think it has something to do with @deep not being respected somehow -- not sure yet.

Here is a snippet from machine.rb

``` ruby
# Walks down the given path.  Each new path that matches the configured
# requirements will be added to this collection.
def walk(path)
  self << path if path.complete?
  path.walk {|next_path| walk(next_path)} unless to_name && path.complete? && !@deep
end
```

I am blocked by this at the moment and could use some guidance as well.

**Comment by peppyheppy** [comment]
UPDATE: I ran some simple tests to see how the state_paths performs and how many paths there are. Wow!

Running object.state_paths with transitions "from" set to varying numbers of "alls":

with one from all transition on the object:
2 (< 0.5 seconds)

with 2 from all transition on the object:
2798 (~ 3 seconds)

with 3 from alls:
102864 (~ 3 minutes)

Scary slow/deep!

Any suggestions for me?

**Comment by peppyheppy** [comment]
I ended up getting what I needed from directly calling:

``` ruby
object.state_events
```

**Comment by paulsturgess** [comment]
I just hit this same recursive issue when using `state_paths`. Switched to `state_events` and everything works.

**Comment by obrie** [comment]
`state_paths` is intended to give you _every_ path possible.  Assuming you don't set the `:deep` option, if you specify a target state it'll give you every path that's possible to that state without using the same transition in a single path.  If you don't set a target state, it'll give you every path that's possible to any state without repeating a transition in a single path.

In your scenario, your state machine has just become so large that the number of possible paths through it is huge.  As you may have noticed, doing things like adding loopbacks multiplies the number of possible paths -- not sure I know enough about graph math to tell you on what order the possibilities are multiplied when a new state is added :)

If all you're looking for are the next possible events / transitions, `state_events` / `state_transitions` is indeed the way to go.  If you're doing more complex analysis on the complexity of your state machine, that's where `state_paths` comes in.
