### ISSUE TITLE
transition :from => all, to => :some_state fails string/symbol test.

### ISSUE THREAD

**Issue by jimjames99** [pluginaweek/state_machine#190]
Hi,

I just upgraded from an earlier version to latest. I have a statemachine in my User model like this:

``` ruby
  state_machine :user_state, :initial => :active do
    state :inactive
    state :active
    state :unregistered
    state :registered
    state :registered_with_credit
    state :canceled

    event :activate do
      transition all => :active, :unless => :active?
      #transition :from => :inactive,    :to => :active
    end

    event :register do
      #transition :to => 'registered', :from => :all
      transition :from => :active,                 :to => :registered
      transition :from => :inactive,               :to => :registered
      transition :from => :unregistered,           :to => :registered
      transition :from => :registered_with_credit, :to => :registered
      transition :from => :canceled,               :to => :registered
    end

    event :cancel do
      transition :from => any, :to => :canceled
    end

  end
```

However, I am getting the error:
`#<StateMachine::AllMatcher:0x007fad9454fd78 @values=[]> state defined as StateMachine::AllMatcher, :active defined as Symbol; all states must be consistent`

I think this is happening in machine.rb line 2219: all my states are symbols except the "any" state which is an AllMatcher. It's in the last block of my code snippet above.

I assume AllMatchers should not be tested for on line 2219, but I'm not quite sure if that's the intent.

Or am I barking up the wrong tree entirely?

Best regards,     Jim.

**Comment by jasdeepsingh** [comment]
I've been fighting with a similar issue. Perhaps, we can look at it together and submit a patch?

Here's a state I have on one of my models:

``` ruby
    state all - [:draft] do
       def custom_method
         puts "output something custom"
       end
    end
```

My problem is that even though the above is outlined in the Documentation - The behaviour is not working as expected. The above code should tack on my `custom_method` to all instances where state `is not` `draft`. In my case - This is not happening.

**Comment by obrie** [comment]
Hey @jimjames99 -

The problem in this case is actually the last event definition:

``` ruby
event :cancel do
  transition :from => any, :to => :canceled
end
```

In this case, `:from => any` isn't really an expected use of the API.  Instead, you would define the transition as follows:

``` ruby
transition :to => :canceled
```

The problem is that, with this syntax use, the values in the hash are interpreted as the real value -- no support for `any` / `all` / `same`.  Let me think about whether this is a scenario worth supporting or not.

**Comment by obrie** [comment]
Thought about this a little more and I think it makes sense to support your use case.  @jasdeepsingh I'm not sure what issue you're running into and whether it's actually related.  I don't seem to be reproducing your issue -- see below:

``` ruby

$: << 'lib'
require 'state_machine'

class User
  state_machine :user_state, :initial => :active do
    state all - [:active] do
      def custom_method
        puts "output something custom"
      end
    end

    event :deactivate do
      transition :active => :inactive
    end
  end
end

user = User.new     # => #<User:0xb709cd1c @user_state="active">
user.custom_method  # => NoMethodError: super: no superclass method `custom_method' for #<User:0xb709cd1c @user_state="active">
user.deactivate     # => true
user                # => #<User:0xb709cd1c @user_state="inactive">
user.custom_method  # => "output something custom"
```

If you're still encountering the issue, feel free to open a new issue.

**Comment by jasdeepsingh** [comment]
@obrie - Thanks for the reply. I'll look into the issue once again and see if I can reproduce it and get back to you with some concrete details/scenario to reproduce this.

Great gem by the way! :+1:

**Comment by jimjames99** [comment]
Ah, got it. I was't sure about that syntax. I should have tried it without the :from!

Awesome gem - love using it.   Jim.

## 

Jim James
