### ISSUE TITLE
calling `#can_<event>?` should not commit to the database

### ISSUE THREAD

**Issue by greggroth** [pluginaweek/state_machine#192]
In Rails, if you have an event set up like so:

``` ruby
class Person < ActiveRecord::Base
   #...
    event :fire do
      transition [:hired] => :fired, if: lambda { |person| person.company.downsize }
    end
   #...
end
```

where a Person `belongs_to :company` and `#downsize` is state_machine event on the Company model.  Calling `@person.can_fire` will call the `person.company.downsize` event when a user might expect it to call `person.company.can_downsize?`.  The best solution to this would probably be to add an `after_event` callback which is called only if the event call returns true.

**Comment by the8472** [comment]
`if: lambda { |person| person.company.downsize }`

This is executed everytime the state machine checks if a transition can be executed. You want to run non-mutating code there, i.e. `person.company.can_downsize?`

The mutating code should go into before/after_transition handlers.

**Comment by greggroth** [comment]
Like you suggest, I've handed it by having a `after_transition` callback, but that is called with the transition happens regardless of which event caused the transition.  I think it would be useful to have an `after_event` callback that is called only when that event is called.  Just because the state change is the same, does necessarily mean you want the same callback.

**Comment by the8472** [comment]
use the :on condition for the callback

**Comment by greggroth** [comment]
Ok that works!  Thanks!  :+1:
