### ISSUE TITLE
Storing user-defined objects with callbacks, branches, events, machine

### ISSUE THREAD

**Issue by the8472** [pluginaweek/state_machine#194]
It would be nice if i could "annotate" the definitions of a state-machine to inspect the annotations while processing the machine in controllers and views.

In my case i'm generating the machines dynamically, which makes it difficult to attach the correct user interface elements to the transitions. Most behavior is in the state machine itself (before/after callbacks, conditions, the state ifself is the information etc.), but the controller logic is disjoint from that.

**Comment by obrie** [comment]
@the8472 Thanks for the suggestion!  I'll be honest this has been proposed many times in the past few years and each time the conclusion has been that the custom data didn't belong in the state machine (or, often, even in the model).  Allowing this type of behavior is a slippery slope and I can imagine it leading to many misuses.

Dynamic state machines are definitely an edge case and an integration very few folks use.  If, in your case, you're building states / events / branches / callbacks from user input, I'd honestly propose having application models with your specific business logic wrapping any references to state_machine definitions (e.g. your own State / Event / Branch models).  Those models would then be backed by the database.

I'm happy to see a feature like this get released as a state_machine extension and watch its usage in the community, but again -- my thinking is that business data / logic related to states / events / branches belongs outside of state_machine.

I'll certainly reopen the issue if there's more discussion to be had.

**Comment by the8472** [comment]
Well, it's not only for dynamic state machines. It's more about the MVC-integration. The state machine is the model-part. But it cannot communicate well with the VC-part.

In our case we expect the transition args to contain certain objects which have to be generated by the controller based on user input. The controller has to know which view components it has to use to generate the necessary objects to pass to the transition. Our syntax is approximately like this:

```
state_machine do
  event :foo
    config.add_components(:comments, :change_reason)
    transition :one => :two
  end

  before_transition :on => :foo do |object, transition|
    object.comments << transition.args.last[:comment]
    object.event_log(transition.args.last[:reason], transition.args.last[:by_user]) 
  end
end
```

I.e. the handlers only take care of the model-level things while the views don't know anything about the state machine and simply prepare objects for consumption by the machine.

What is missing is a layer to bind these things together.
