### ISSUE TITLE
attr_readonly within states?

### ISSUE THREAD

**Issue by lukes** [pluginaweek/state_machine#195]
Hi, 

We're trying to use `attr_readonly` within a `state` block in the same way that validations for states work.

```
  state :published do
    attr_readonly :name
  end
```

However the `attr_readonly` seems to be being applied to all of our states. 

Is there a way that `attr_readonly` can be applied to only specific states?

Luke

**Comment by the8472** [comment]
States just capture the methods defined in a block, not some class-level configuration stuff.

**Comment by obrie** [comment]
The reason for the issue was commented on in #59.  Unfortunately, this isn't a possible use of `attr_readonly`.  Sorry!
