### ISSUE TITLE
much record transition performance

### ISSUE THREAD

**Issue by chengdh** [pluginaweek/state_machine#202]
i use state_machine ,in my controller ,i have 3000+ object will invoke state_machine event,every tranistion generate a update sql,
so the controller action very slow ,is there a batch upate for performance?

**Comment by the8472** [comment]
Have you tried wrapping them in a transation? That'll still issue the individual update statements, but at least you're saving on the transaction overhead.

**Comment by obrie** [comment]
@the8472's suggestion is the same I would have made -- transactions are the best way to go.  There's no concept of batch updates in state_machine.

Good question!
