### ISSUE TITLE
Doesn't Appear to work with later versions of mongoid 2

### ISSUE THREAD

**Issue by pvertenten** [pluginaweek/state_machine#203]
Latest version of mongoid 2 is 2.4.6

From code the code 

version '2.0.x - 2.2.x'
version '2.0.x'

**Comment by obrie** [comment]
Thanks for reporting this -- the `versions.rb` file doesn't actually define what versions are supported, but instead provides support for older versions whose integration has changed.  Nonetheless, there were indeed issues with newer versions which have since been resolved.
