### ISSUE TITLE
mongoid - using field aliasing, state machine only work if use real field name

### ISSUE THREAD

**Issue by fabioperrella** [pluginaweek/state_machine#204]
Hi, using mongoid v3, in my model I have this:

field :st, as: :status

and this:

state_machine, :initial => :enabled do
event :disable do
.....

I noticed the state machine only works if doing llike this (using the field real name):

state_machine :st, :initial => :enabled do
event :disable do

I think the correct would be using the field alias name, not the field real name, isn't it?

**Comment by obrie** [comment]
Thanks for the heads up!  Indeed state_machine was not properly detecting aliased fields.  This should be fixed now and will be included in the next release.
