### ISSUE TITLE
Doesn't honor ActiveRecord::Base.observers.disable(:all)

### ISSUE THREAD

**Issue by johnkchow** [pluginaweek/state_machine#205]
In our `spec/spec_helper.rb`, it  runs `ActiveRecord::Base.observers.disable :all` for each example (wrapped in a `config.before(:each)` block). When our specs run where we trigger an event, it will call **all** registered observer methods. This is causing a huge seg fault in our test suite.

A solution would be for the gem to honor `AR::Base'`s disabled observers, and only call the transition hooks.

**Comment by johnkchow** [comment]
Here's the seg fault trace:

https://gist.github.com/1045aba75ba212ba9bcf

**Comment by johnkchow** [comment]
After running our specs, it appears that the seg fault occurs consistently during examples where we fire off a state_machine event. Going to do more investigation, but it's very concerning.

**Comment by johnkchow** [comment]
I realize that the repo has the test that honors the observers being enabled/disabled. For anyone who has problems with this, just point your Gemfile to the latest commit. 

It'd be nice to push an update to RubyGems btw :)

**Comment by iRonin** [comment]
I've just run into the same issue.
The most recent state_machine-1.1.2 has this issue, the most recent master doesn't.
Any idea where the fix is going to be released?

**Comment by johnkchow** [comment]
@iRonin turns out the seg fault wasn't from the state_machine library but because (for some reason unknown to me) that by compiling our Ruby (1.9.3-p194) with GCC that was > 4.2, that was causing the seg faults. This happened on our Ubuntu 12.04 machines.

We recompiled Ruby with GCC 4.2 and it's golden. If you're on Mac, don't use LLVM.

**Comment by iRonin** [comment]
@jkchow I was referring to the the fact that state_machine doesn't honor ActiveRecord::Base.observers.disable(:all).

**Comment by johnkchow** [comment]
Works for me in commit 40ae5757cba9a4ce9e8faf889fec435370daf929, and there's even a test on it for AR:

https://github.com/pluginaweek/state_machine/blob/master/test/unit/integrations/active_record_test.rb#L1656-L1679

**Comment by iRonin** [comment]
Yes, it works in the commit you mentioned but it doesn't work in the latest version uploaded to rubygems and that's what  I meant by my question.

**Comment by obrie** [comment]
@iRonin now that I'm back from hiatus, I will be trying to get a new release out within the next few weeks.  Stay tuned.

**Comment by iRonin** [comment]
@obrie thanks for the update! :)
