### ISSUE TITLE
Can't get transition callbacks to work when using Mongoid 3

### ISSUE THREAD

**Issue by supairish** [pluginaweek/state_machine#208]
Is this a known issue?

**Comment by ndelage** [comment]
I'm having trouble as well. I'm sure my observer is wired up because I'm seeing regular Mongoid callbacks being run (like before_save). But none of the state_machine callbacks are ever triggered.

**Comment by ndelage** [comment]
Are you using Mongoid 3.X ? I got the test suite running locally and with 3.0.13 I have 179 errors. I'm going to try and come up with the fixes to support 3.X

**Comment by obrie** [comment]
Hey guys -

Thanks for letting me know that you're running into this issue.  I've made several changes to support Mongoid 3.x.  A new version should be released with these changes in the next few weeks.  I've added more tests to validate the observer / callback functionality.  If you're still encountering issues, let me know (with any debugging / steps to reproduce) and I'll reopen the issue.
