### ISSUE TITLE
Is there a way to specify a method as the state accessor?

### ISSUE THREAD

**Issue by pi3r** [pluginaweek/state_machine#211]
Hi, 

I'm wondering if there is any way to specify a method as the state accessor ? 

like:

``` ruby
state_machine proc { another_object.state } do
end
```

Idem for the state update method.

Cheers

**Comment by alexanderko** [comment]
Hi, 

You can just define state method that returns String. I have used this to provide state name that depends on set of several object properties. For state update you should have state=

``` ruby
def state
  another_object.state
end
```

Best regards, Alexander

**Comment by pi3r** [comment]
Thanks, i'll try that !
