### ISSUE TITLE
Select before transition

### ISSUE THREAD

**Issue by kgeoir** [pluginaweek/state_machine#216]
I have an admin interface where I have some button to validate my record state. My controller code is:

@instance = MyModel.find(params[:id])
@instance.fire_sate_event(params[:event])

in my model I do:

after_transition :state_a => :state_b do
// Critical code
end

after_transition :state_a => state_c do
// Other critical code
end

the problem of such code is the concurrency: the select done in the controller: @instance = ARobj.find(params[:id]) is outside the transaction so if a contrary event occur between the select and the transaction, value in DB has been changed so the instance is deprecated and the state is undetermined.

Anyway to prevent such issue?

**Comment by the8472** [comment]
Just wrap everything in a transaction?

**Comment by obrie** [comment]
@kgeoir This issue has been addressed in #241 -- the tl;dr; is that optimistic locking should be used.
