### ISSUE TITLE
Problems Testing With Capybara

### ISSUE THREAD

**Issue by simonmorley** [pluginaweek/state_machine#217]
I'm not sure if this is actually a bug but I simply cannot get my tests to pass when using state_machine (1.1.2) and capybara (2.0.0) in Rails 3.2.9. 

My test (simplified) looks like this:

```
describe "Shouldn't allow you to move past the pending state without a user" do
  it "should create a product and go through steps" do
    order = FactoryGirl.create(:product_order_full)
    visit order_path(order)
    order.state.should eq("pending")
    click_button 'Next Stage'
    order.state.should eq("shipped")
    ...
   end 
 end
```

In my view I have a button with the name 'next_state' which I'm picking up in the controller:

```
 if params[:next_state]
     @order.next!
  elsif params[:take_me]
     ....
  end
```

In the 'real-world' this works fine and moves the order to the next state. However, in my tests, this fails with:

```
   expected: "shipped"
   got: "pending"
```

Even though, if I put the page.body, I can see the state is set to shipped... Really odd.

So, I have tried forcing the the state via next! in the test and this works.

Any suggestions?

**Comment by kidoman** [comment]
Not very sure, but just a suggestion.

Why would the already loaded order instance reflect the changed attribute? The change has happened behind the scenes for this order instance.

Try loading the instance again.

http://apidock.com/rails/ActiveRecord/Persistence/reload

**Comment by simonmorley** [comment]
I've give it a try. It's pretty intermittent - weird in itself. Have tried including a sleep but will try the reload.

**Comment by simonmorley** [comment]
Like you said, the instance needs to be reloaded. In the end, I did another find for the item in question. Nothing wrong with capybara or state_machine ;)

A quick note to say how B(_(_&^*^%y amazingly great state_machine is! Saved me hours and hours.
