### ISSUE TITLE
Return list of all states?

### ISSUE THREAD

**Issue by lascarides** [pluginaweek/state_machine#224]
Is it possible to return an array of all states (not just the possible transitions from a given state)? 

Looked for it in the documentation but didn't find it. Thanks in advance!

**Comment by the8472** [comment]
`YourModel.state_machines[:your_state].states.keys`

see http://rdoc.info/github/pluginaweek/state_machine/master/frames/StateMachine/ClassMethods

**Comment by lascarides** [comment]
thanks much! would not have put that together on my own.
