### ISSUE TITLE
params to not save after event

### ISSUE THREAD

**Issue by shingara** [pluginaweek/state_machine#234]
Hi,

I use state_machine with some Mongoid document. if I fire an event a save of this object is fire. It can be good to fire event without saving document. Just change the state and raise exception if the change can be allow.

**Comment by obrie** [comment]
Hi @shingara -

You can actually already do this.  See the `state_machine` docs @ http://rdoc.info/github/pluginaweek/state_machine/master/StateMachine/MacroMethods:state_machine.  By default, Sequel integrations use `:save` as the `:action` configuration.  By setting `:action` to `nil`, the machine won't automatically save your object.

**Comment by shingara** [comment]
thanks, it wasn't really clear to me, this option `:action` is not define in the readme. But in the API all is clear, thanks.
