### ISSUE TITLE
Supply status_upstream_of?, terminal_state? and terminal_states methods

### ISSUE THREAD

**Issue by hlascelles** [pluginaweek/state_machine#237]
We often need to know terminal and flow state information, and have put together methods that can be called on model instances.

```
  def status_upstream_of?(status)
    status_name != status && (status_paths(deep: true, guard: false).to_states.include? status)
  end
```

and

```
  def terminal_state?
    status_paths(guard: false).all? { |sp| sp.to_name == self.status_name }
  end
```

We'd also like to know, given a class, all terminal states. 

Before I head off into the code, is there a way to do this quickly?

Thanks!

**Comment by the8472** [comment]
for terminal states:

YourModel.state_machines[:machine_name].states.select{|st| st.final?}

**Comment by hlascelles** [comment]
Spot on! Thanks very much Mr 8472...

**Comment by obrie** [comment]
@the8472 thanks for jumping in and providing the solution!
