### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by dwilkie** [pluginaweek/state_machine#241]
I ran into a situation where a race condition was causing the state to be updated incorrectly in Rails. Here's the example:

```
state_machine :initial => :pending_delivery do
  state :pending_delivery, :queued_for_smsc_delivery, :delivered_by_smsc

  event :update_delivery_status do
    transition([:pending_delivery, :queued_for_smsc_delivery] => :delivered_by_smsc, :if => :delivery_succeeded?)

    transition(:pending_delivery         => :queued_for_smsc_delivery)
  end
end
```

In one rails worker process I had this code like this:

```
reply = Reply.find(id)
# do some stuff
reply.update_delivery_status
```

And in another web process I had similar code like this:

```
reply = Reply.find(params[:id])
reply.delivery_code = params[:status]
reply.update_delivery_status
```

What happened was that the code in the worker process was running and the state was originally `pending_delivery` but then, concurrently the web process updated the state to `delivered_by_smsc` so when the worker called `update_delivery_status` the state was changed back to `queued_for_smsc_delivery` instead of remaining at `delivered_by_smsc`

One might think that putting a `reload` in immediately before calling `update_delivery_status` might solve the problem but the update can happen at any time, so you really need a database level constraint.

I looked into the state_machine code and realized you can pass an `action` parameter to the `state_machine` which will override the default `save` action for active_record.

This was my solution (note the `action` attribute)

```
state_machine :initial => :pending_delivery, :action => :save_with_state_check do
  state :pending_delivery, :queued_for_smsc_delivery, :delivered_by_smsc

  event :update_delivery_status do
    transition([:pending_delivery, :queued_for_smsc_delivery] => :delivered_by_smsc, :if => :delivery_succeeded?)

    transition(:pending_delivery         => :queued_for_smsc_delivery)
  end
end
```

Then later in my class I had

```
class Reply < ActiveRecord::Base
  state_machine..... do
  end

  private

  def save_with_state_check
    if valid?
      state_attribute = self.class.state_machine.attribute
      self.class.update_all(
        { state_attribute => state },
        { self.class.primary_key => id, state_attribute => state_was }
      ) == 1
    end
  end    
end
```

Note that `save_with_state_check` still calls `valid?` like `save` would have done but it adds a condition to the `UPDATE` statement that the `state_attribute` must have been the previous value (`state_was`). This makes sure on the DB level that the state is transitioning correctly.

I think that this behavior should be the default for the ActiveRecord Integration at least, however it might need some additional tweaking to handle the case where the model is a new record.

Any thoughts?

@obrie if you agree with this behavior I'll try to wrap it into a pull request for you.

**Comment by the8472** [comment]
I would say that wrapping the load-modify-store cycle into a transaction (`serializeable` or `select ... for update`) would do the job too.

**Comment by dwilkie** [comment]
@the8472 I don't see how wrapping this in a transaction helps here since the check needs to be at the database level. Can you give me an example?

**Comment by agibralter** [comment]
A transaction ensures that the state remains consistent at the database
level. Are you using MySQL InnoDB? Then an ActiveRecord transaction can
eliminate race conditions provided you write the application logic
correctly.

urtak.com / @urtak http://twitter.com/urtak

**Comment by dwilkie** [comment]
I'm using Postgres but I don't think that matters. From my understanding a transaction is used to ensure that SQL statements are only permanent if they all succeed. Taking the example from the Rails docs:

```
ActiveRecord::Base.transaction do
  david.withdrawal(100)
  mary.deposit(100)
end
```

So Mary is only deposited if David's withdrawal succeeds.

This case is a different situation. There is only one SQL statement being run here namely an UPDATE statement on the record to update the state. You need to ensure that the update is correct at the DB level.

From my understanding there are only 4 possible solutions:
1. The one I show above (which I think needs a discussion of whether this should be default behavior for the state machine gem for active_record)
2. A database trigger to check the state change is correct. (I don't like this solution because it requires you to duplicate the state machine logic on the DB level)
3. Rails' optimistic locking. See http://api.rubyonrails.org/classes/ActiveRecord/Locking/Optimistic.html. (I think this may be overkill since you only want to check that the state follows the state machine)
4. Rails' pesimistic locking. See http://api.rubyonrails.org/classes/ActiveRecord/Locking/Pessimistic.html. (Again not sure if this is a good idea)

**Comment by the8472** [comment]
Locking (either optimistic or pessimistic is a design decision) + Transactions is pretty much what you want. It ensures that a write with dependencies on stale data will fail and rollback all changes done during the transaction.

That's really standard database fare and not a state machine issue.

**Comment by dwilkie** [comment]
@the8472 sorry I'd have to disagree with you there. The role of a state machine (and the gem) is to ensure that an object stays in valid state through valid transitions. For activerecord integration this means ensuring the state is correct on the db level.

Again i don't see how transactions can help here. There is only one SQL statement being executed. Feel free to enlighten me how you would solve this problem using a transaction.

**Comment by the8472** [comment]
> There is only one SQL statement being executed.

There isn't. You're first loading the object, which is a `SELECT` statement, then you're modifying the record, then you're writing the modified state with an `UPDATE` statement.

> is to ensure that an object stays in valid state through valid transitions

You see, the _object_ stays valid as its state does not change. The value only changes on the database. You will face exactly the same problem with _anything_ using active record. E.g. two people concurrently editing an object will get you the same race conditions in validations. A validation may succeed despite the two edits combined making the object non-valid.
It's not specific to state_machine and therefore you're attacking the problem at the wrong level.

This is a persistence problem and should be treated as the persistence layer. The usual solution to this kind of problem is using locking reads in a transaction or MVCC (optimistic locking). Or you ignore races and risk data inconsistencies like many people seem to do - which is the default mode in activerecord.

**Comment by dwilkie** [comment]
Ok, I _still_ don't see how a transaction can be used here, feel free to show me with an example, but your basically saying that I should use optimistic locking or pessimistic locking. I outlined these as one of the 4 possible solutions above, I just think that solution 1 is better for this case.

**Comment by the8472** [comment]
> Ok, I still don't see how a transaction can be used here

a) With the `SERIALIZABLE` isolation level.
b) With pessimistic locking... it requires transactions

For optimistic locking it's not essential but improves consistency when loading relations and things like that through `REPEATABLE_READ` semantics.

> I just think that solution 1 is better for this case.

Dirty field checking doesn't provide race-free behavior because state conditions (the `:if => ...`) can depend on other fields and even on relations too.

**Comment by agibralter** [comment]
Totally agree with @the8472 

``` ruby
Reply.transaction do
  reply = Reply.find(id)
  # do some stuff
  reply.update_delivery_status
end
```

How is that different than the withdrawal example you gave as an example of when transactions are necessary?

**Comment by agibralter** [comment]
I suggest you try it with two `rails c` sessions and see if it works.

**Comment by dwilkie** [comment]
@agibralter your suggestion doesn't solve the issue.

The example you gave is different from the withdrawal example because `Reply.find(id)` will always be successful so `reply.update_delivery_status` will result in a write to the db since it also will not raise an error. As explained in the Rails documentation here: http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html for the withdrawal example:

```
ActiveRecord::Base.transaction do
  david.withdrawal(100)
  mary.deposit(100)
end
```

This example will only take money from David and give it to Mary if neither withdrawal nor deposit raise an exception. Exceptions will force a ROLLBACK that returns the database to the state before the transaction began. 

With the state machine issue there are no exceptions raised, and even if there was it still wouldn't prevent the race condition because the replies state could be updated externally after the `Reply.find` call leaving `reply` as a stale object.

Therefore you either have to use optimistic locking, pessimistic locking or the solution I propose above.

**Comment by agibralter** [comment]
@dwilkie you should design your state transitions such that they will raise exceptions in race conditions.

Don't the implementations of `withdrawal` and `deposit` require finds and updates just as you suggest is the case with your transitions?

**Comment by dwilkie** [comment]
@agibralter even if the state transition did raise an exception on an incorrect state transition you still cannot solve the problem of a race condition with a transaction, because the state can be updated at anytime. Here is the proof with a failing spec.

```
describe Reply do
  it "should handle a race condition" do
    reply = create(:reply, :state => :pending_delivery)
    reply.update_delivery_state
    reply.reload.should be_delivered_by_smsc # fails here
  end
end

def Reply
  state_machine :initial => :pending_delivery do
    state :pending_delivery, :queued_for_smsc_delivery, :delivered_by_smsc

    event :update_delivery_status do
      transition([:pending_delivery, :queued_for_smsc_delivery] => :delivered_by_smsc, :if => delivery_succeeded?
      transition(:pending_delivery         => :queued_for_smsc_delivery)
    end
  end

  def update_delivery_state(options = {})
     @delivery_state = options[:state]
     Reply.transaction do
      reload
      Reply.update_all({:state => :delivered_by_smsc}, :id => id) # creates the race condition in practice this would happen in an external process
      update_delivery_status # reply is stale so it updates the state to "queued_for_smsc_delivery"
    end
  end

  def delivery_succeeded?
    @delivery_state == "delivered"
  end
end
```

**Comment by agibralter** [comment]
What happens if you use `update_delivery_state!`?

urtak.com / @urtak http://twitter.com/urtak

**Comment by dwilkie** [comment]
Same issue since the object is stale, it loaded as 'pending_delivery' and in between  e.g. by another process it's updated to "queued_for_smsc_delivery". Therefore you need a check on the DB level. In this Railscast (pro episode) (http://railscasts.com/episodes/59-optimistic-locking-revised) Ryan Bates shows how to use Rails' optimistic locking.

At the end though he shows an alternative technique which doesn't require the extra column. That's where I got the idea for the implementation I show above.

**Comment by the8472** [comment]
Let me put it differently: You're not using locking in your application. Which means that race conditions can and will happen with **any and all** read-modify-update cycles in your application. If you choose to accept race conditions everywhere in your application, why should state_machine go out of its own way to bypass activerecord (it's just calling `.save()` internally) and manually create update statements to avoid race conditions when you're not even avoiding them in your own code?

You're pushing down persistence layer concurrency issues to each end consumer of the persistence layer instead of fixing them once and for all by enabling a built-in feature of the persistence layer.

And another issue is that dirty field checks **don't actually work**. Consider the following scenario

``` ruby
class ModelA < ActiveRecord:Base
  validates do
     errors.add :base, :only_one_flag_can_be_true if self.some_flag  && self.model_b.some_flag
  end
end

class ModelB < ActiveRecord::Base
  belongs_to :model_a, :validate => true
end


a = ModelA.preload(:model_b).first

Thread.new do
  b = ModelB.preload(:model_a).first
  b.some_flag = true
  b.save!
end

a.some_flag = true
a.save! # success!

a = ModelA.first
a.valid? # false!
```

Even with dirty field checks this will fail because different fields have been modified in different models. Each one will only see one of the two flags set to `true` and thus the validation passes and only those fields would be dirty and checked in the UPDATE statement. But in the end you end up with an object failing the validation.

**Comment by obrie** [comment]
Thanks for everyone's input on this.  @dwilkie the issue you raise is interesting and I appreciate all of the thought and effort that's gone into it.  I'll admit I agree with @the8472 here -- optimistic locking is the solution I've always used in situations like this.  It's basically what you're proposing but in a generic way that can be used to ensure consistency across all of your record's attributes.  If you'd prefer to use `state` as your version locking mechanism, maybe that's okay for your use case, but I wouldn't recommend it nor would I want to make that an official feature of the library.  Base on previous experience, I would consider that an edge case.

If there are strong opinions that the Rails built-in locking mechanism is too much overhead, I'd encourage developing an extension that allows you to use a separate field.

Thanks again for the interesting discussion!
