### ISSUE TITLE
Plans to cut v1.1.3 or v2?

### ISSUE THREAD

**Issue by MattRogish** [pluginaweek/state_machine#242]
Hi,

v1.1.3 was released a year ago; just curious if there are any plans to release the latest changes as a gem update (I'm not sure if they appear to be breaking necessitating a v2)

Thanks!!
## 

Matt

**Comment by obrie** [comment]
There are plans to cut v1.2 within the next week... soon :)

**Comment by MattRogish** [comment]
Thanks! :D
