### ISSUE TITLE
Validator method is only be called on last instance of validation

### ISSUE THREAD

**Issue by jisk** [pluginaweek/state_machine#245]
If you use a custom validation method with the "validate" clause in more than one state, it is only called on the last state that mentions that validation method.

For example - in the following code, the date_of_expiry must be present validator works for entering both expired and expired_foreign states, but the custom date_of_expiry_must_be_in_the_past method is only called for the last defined state, expired_foreign.

Correct behaviour should be calling the validation method for both states.

``` ruby
state :expired do
  validates :date_of_expiry, presence: true
  validate :date_of_expiry_must_be_in_the_past
end

state :expired_foreign do
  validates :date_of_expiry, presence: true
  validate :date_of_expiry_must_be_in_the_past
end   

**snip**

def date_of_expiry_must_be_in_the_past
  logger.debug("validating date of expiry is in the past")
  if !date_of_expiry.blank? and date_of_expiry >= Date.today
    errors.add(:date_of_expiry, "must be in the past to expire this record")
  end
end
```

**Comment by obrie** [comment]
Hey @jisk -- see #198 for an explanation

**Comment by jisk** [comment]
Thanks @obrie. I didn't see that. I'll use the workaround.
