### ISSUE TITLE
Quick Question Dynamic States and Transition Events

### ISSUE THREAD

**Issue by endzyme** [pluginaweek/state_machine#249]
I am not seeing any clear documentation on how one would make state transition actions on state changes. Is there something I am missing somewhere?

**Comment by obrie** [comment]
Not sure I follow the question -- can you give an example?

**Comment by endzyme** [comment]
Sure, 

Using [the docs](https://github.com/pluginaweek/state_machine/#static--dynamic-definitions) you show how to define dynamic states and interactions. Unfortunately I am not seeing where I'd add something like 

``` ruby
before_transition any => :some_state, :do => :some_method
```

**Comment by the8472** [comment]
`before_transition` is just a method on the `Machine` instance, you can call it and pass arguments from hashes as needed at the same place you call the `transition` method.

**Comment by obrie** [comment]
Indeed @the8472 is correct -- you'd want to do something like...

``` ruby
class Vehicle
  # ...

  def machine
    vehicle = self
    @machine ||= Machine.new(vehicle, :initial => :parked, :action => :save) do
      vehicle.transitions.each {|attrs| transition(attrs)}

      before_transition any => :some_state, :do => lambda {|transition| vehicle.some_method(transition)}
    end
  end
end
```

Unfortunately I don't think the `:do => :symbol` technique would work because it doesn't get executed within the context of your `Vehicle` instance.

It's not ideal, but it ought to do the trick.  With a little metaprogramming magic in the `Machine` class example, I'm sure you could get the `:do => :symbol` technique to work.

**Comment by endzyme** [comment]
thanks guys! appreciate the help!

**Comment by the8472** [comment]
Instead of instantiating a machine in an instance you might be able to dynamically create subclasses instead and build the machine on the class level. This is quite expensive, but gives you all the class-level integration. Might be an option if the user-configured machines don't change too often.
