### ISSUE TITLE
using Factories for testing

### ISSUE THREAD

**Issue by rudi911** [pluginaweek/state_machine#259]
I have issues with FactoryGirl as well as Fabrication when I want to initialize a class containing a stat_machine. I have the feeling it's related to having to include the "super()" call in the initialize block.
Have you been able to successfully use the state_machine with these kind of testing gems?

**Comment by agibralter** [comment]
I've been using state_machine with FactoryGirl for a long time... No issues so to speak.

​What problem are you experiencing?

**Comment by rudi911** [comment]
I get an error pointing to the initialize call of my model, while the only reason I have the initialize method is for state_machine. the intialize method of my order model is:

  def initialize
    super()  
  end

The error I get when I do Fabricate :order :
1.9.3-p194 :001 > Fabricate :order
   (0.2ms)  SAVEPOINT active_record_1
  User Exists (1.5ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = 'tester0@tester.nl' LIMIT 1
  SQL (3.5ms)  INSERT INTO "users" ("account_type", "created_at", "current_sign_in_at", "current_sign_in_ip", "email", "encrypted_password", "expires_at", "last_sign_in_at", "last_sign_in_ip", "remember_created_at", "reset_password_sent_at", "reset_password_token", "sign_in_count", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) RETURNING "id"  [["account_type", "free"], ["created_at", Thu, 06 Jun 2013 13:07:52 UTC +00:00], ["current_sign_in_at", nil], ["current_sign_in_ip", nil], ["email", "tester0@tester.nl"], ["encrypted_password", "$2a$10$OSx4eLIQJGYeIAaTIIchZORLNaLQjb3yjI7QAz.gvtsELW/H3C9qK"], ["expires_at", nil], ["last_sign_in_at", nil], ["last_sign_in_ip", nil], ["remember_created_at", nil], ["reset_password_sent_at", nil], ["reset_password_token", nil], ["sign_in_count", 0], ["updated_at", Thu, 06 Jun 2013 13:07:52 UTC +00:00]](0.1ms)  RELEASE SAVEPOINT active_record_1
   (0.4ms)  SAVEPOINT active_record_1
  SQL (11.9ms)  INSERT INTO "order_lines" ("created_at", "order_id", "price", "product_id", "quantity", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["created_at", Thu, 06 Jun 2013 13:07:52 UTC +00:00], ["order_id", nil], ["price", #<BigDecimal:7fba310cc798,'0.999E1',18(45)>], ["product_id", nil], ["quantity", 1], ["updated_at", Thu, 06 Jun 2013 13:07:52 UTC +00:00]](0.4ms)  RELEASE SAVEPOINT active_record_1
   (0.3ms)  SAVEPOINT active_record_1
  SQL (18.1ms)  INSERT INTO "transactions" ("bank", "created_at", "date", "order_id", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["bank", "MyString"], ["created_at", Thu, 06 Jun 2013 13:07:52 UTC +00:00], ["date", Thu, 30 May 2013 13:13:55 UTC +00:00], ["order_id", nil], ["updated_at", Thu, 06 Jun 2013 13:07:52 UTC +00:00]](0.3ms)  RELEASE SAVEPOINT active_record_1
ArgumentError: wrong number of arguments (2 for 0)
    from /Users/Rudi/devel/locationwise/app/models/order.rb:52:in `initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/fabrication-2.5.4/lib/fabrication/generator/active_record.rb:8:in`new'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/fabrication-2.5.4/lib/fabrication/generator/active_record.rb:8:in `build_instance'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/fabrication-2.5.4/lib/fabrication/generator/base.rb:13:in`build'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/fabrication-2.5.4/lib/fabrication/generator/base.rb:26:in `create'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/fabrication-2.5.4/lib/fabrication/schematic/definition.rb:62:in`block in fabricate'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/fabrication-2.5.4/lib/fabrication/schematic/definition.rb:61:in `instance_eval'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/fabrication-2.5.4/lib/fabrication/schematic/definition.rb:61:in`fabricate'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/fabrication-2.5.4/lib/fabrication/fabricator.rb:10:in `fabricate'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/fabrication-2.5.4/lib/fabrication.rb:51:in`Fabricate'
    from (irb):1
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in`start'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

**Comment by rudi911** [comment]
I also get an issue when creating a new instance with additional parameters. Creating an instance and then assigning the attribute values goes okay.

1.9.3-p194 :001 > o = Order.new(number: 'sd')
ArgumentError: wrong number of arguments (1 for 0)
    from /Users/Rudi/devel/locationwise/app/models/order.rb:52:in `initialize'
    from (irb):1:in`new'
    from (irb):1
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in`start'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

**Comment by agibralter** [comment]
@rudi911 it would be helpful if you pasted your code, not just the errors.

**Comment by rudi911** [comment]
You've got a point...

class Order < ActiveRecord::Base
  attr_accessible :number

  belongs_to :user
  has_one :transaction
  has_many :order_lines

  before_destroy :can_delete?

  scope :current_orders, lambda { |user|
    where('user_id = ?', user.id)
  }

  TAX = 0.21

  state_machine :status, initial: :open do

```
state :open      # order is open and can be deleted
state :payed     # order is payed, no incoice has been sent yet
state :invoiced  # invoice has been sent
state :closed    # order is closed and can be payed

event :pay do
  transition open: :closed
end

event :payment_succeeds do
  transition closed: :payed
end

event :payment_fails do
  transition closed: :open
end

event :generate_invoice do
  transition payed: :invoiced
end

state :payed, :closed, :invoiced do
  def can_delete?
    false
  end
end

state :open do
  def can_delete?
    true
  end
end
```

  end

  def initialize
    super()  
  end

  def order_number
    "loc-%.6d" % id
  end

  def total_amount
    amount = 0.00
    orderlines = OrderLine.where(order_id: id)
    orderlines.each do |line|
      amount += line.price
    end

```
amount
```

  end

  def total_tax
    amount = 0.00
    orderlines = OrderLine.where(order_id: id)
    orderlines.each do |line|
      amount += line.price
    end

```
amount * TAX
```

  end
end

**Comment by agibralter** [comment]
Why do you have

``` ruby
def initialize
  super()
end
```

in your class?

**Comment by rudi911** [comment]
@agibralter The manual says that the call to super() should be included in the initialize. From the docs: 

Note the comment made on the initialize method in the class. In order for state machine attributes to be properly initialized, super() must be called. See StateMachine::MacroMethods for more information about this.

**Comment by agibralter** [comment]
@rudi911 That's not for ActiveRecord models. If you look up in that example, it's explaining how to use state_machine with a plain old ruby object... And it's also, _IF_ you need to use an `initialize` method. And in general, you _shouldn't_ use `initialize` for ActiveRecord objects: http://blog.dalethatcher.com/2008/03/rails-dont-override-initialize-on.html – I know the article is old, but I'm pretty positive the rule still holds.

**Comment by rudi911** [comment]
I'll check again, all my test failed when I removed it

**Comment by agibralter** [comment]
Removed the whole method or the call to super?

**Comment by rudi911** [comment]
removing the call to super() gives a lot of errors, removing the initialize method completely makes everything green again. Thanks for your support.

**Comment by agibralter** [comment]
@rudi911 cool, glad it worked!

Yeah, in general, with ActiveRecord you never want to override initialize unless you absolutely have to for some specific reason. Generally you want to use an after_initialize callback: http://guides.rubyonrails.org/active_record_validations_callbacks.html#after_initialize-and-after_find
