### ISSUE TITLE
before_transition works, after_transition fails on Rails 4/Mongoid

### ISSUE THREAD

**Issue by nofxx** [pluginaweek/state_machine#277]
Lost some time on this one... only here?
As 'fails' I mean wont run, tryed some raise() there and nothing happens.

``` ruby
class Order
  include Mongoid::Document

  state_machine :state, :initial => :created do

    before_transition :on => :pay do |o|
    #... WORKS!

    after_transition :on => :pay do |o|
    # ... NOTHING

  end
end
```

Rails 4, Mongoid 4

**Comment by mensfeld** [comment]
+1

**Comment by aganov** [comment]
+1 Anyone got any idea how to quick fix this?

**Comment by tagrudev** [comment]
+1

**Comment by aganov** [comment]
Somehow this commit is breaking the `after_transition` callback https://github.com/mongoid/mongoid/commit/8c23304dcb56e3c2830f8e1f98b0ad01a7f8c3da

**Comment by we4tech** [comment]
hi @aganov is it still pending pull request ? I just stucked with the same issue. after_transition doesn't fire up. Can we get it merged ?

**Comment by Erol** [comment]
@aganov @pluginaweek Any chance that this will get merged soon?

**Comment by kylemacey** [comment]
+1

**Comment by thijsc** [comment]
Also ran into this bug, would be great to get a fix merged.

**Comment by thijsc** [comment]
@aganov @pluginaweek Is there any way I can help getting this fixed?

**Comment by aganov** [comment]
@thijsc https://github.com/aganov/state_machine/commit/88e45a1b1622d7748933bc941e7e9b08b3045a94

**Comment by thijsc** [comment]
@aganov I've confirmed that that fix works, but the pull is probably not mergable yet since there's no test for the fix. I'd be happy to see if I can help with that?

**Comment by momelnyk** [comment]
+1 for tests and merge

**Comment by thijsc** [comment]
If somebody creates a good pull request for this, will it get merged? Mongoid 4 release is getting pretty close and it would be good to have this in an official release.

cc @aganov @pluginaweek

**Comment by yudho** [comment]
I could reproduce the same behavior. Before transition is working, while after is not called. Really appreciate for the fix.

**Comment by localredhead** [comment]
+1 please

**Comment by helmerj** [comment]
+1

**Comment by max-konin** [comment]
+1

**Comment by gemtainers** [comment]
Have an idea about mainaining #331

**Comment by mvleo-github** [comment]
+1

**Comment by aganov** [comment]
This repository isn't supported anymore... Consider using https://github.com/state-machines/state_machines-mongoid instead

**Comment by mensfeld** [comment]
@aganov then maybe you should mark it in readme as open for adoption

**Comment by nofxx** [comment]
Thanks @aganov. Also, another option is 'AASM'.

**Comment by aganov** [comment]
@mensfeld I'm not the author of this gem, latest commit is from May 7, 2013
@nofxx yes AASM is good too, but `state-machines/state_machines-mongoid` is a drop in replacement...

**Comment by mensfeld** [comment]
@aganov  true - sorry
@obrie  - my question is for you then I assume
