### ISSUE TITLE
No documentation on inheritance

### ISSUE THREAD

**Issue by stevecd** [pluginaweek/state_machine#286]
I haven't been able to find anything on inheritance.  How would one go about modifying/adding to inherited states and events?  Unless I should be able to infer this from current documentation, it might be worth adding, I've found at least two others asking the same question.

**Comment by the8472** [comment]
as soon as you call to the `state_machine`  class method in a subclass everything gets duped over to the subclass and you can re-open events, add new transitions etc.

Removing stuff is more difficult, but i think i've seen a reset method somewhere.

**Comment by stevecd** [comment]
I see, thanks.  I guess that might be obvious enough.
