### ISSUE TITLE
NoMethodError: protected method `around_validation'  in Rails 4.1.0.beta1

### ISSUE THREAD

**Issue by seuros** [pluginaweek/state_machine#295]
```
Store.first.save
  Store Load (0.9ms)  SELECT  "stores".* FROM "stores"   ORDER BY created_at LIMIT 1
   (0.2ms)  BEGIN
   (0.1ms)  ROLLBACK
NoMethodError: protected method `around_validation' called for #<StateMachine::Machine:0x007f674cc70f78>

```

The model has just statemachine

```
  belongs_to :vendor
  state_machine :state, :initial => :new do
  end
```

**Comment by marclennox** [comment]
+1

**Comment by seuros** [comment]
@marclennox , you can use my fork for now .

**Comment by marclennox** [comment]
Awesome thanks!

**Comment by hayesr** [comment]
I can confirm that moving `around_validation` out from under protected works in Rails 4.1 beta1. Also, tests pass for state_machine. (didn't run appraisals)

**Comment by nthj** [comment]
:+1: 

If you'd like a quick hack, I threw this in my initializers:

```
# Rails 4.1.0.rc1 and StateMachine don't play nice

require 'state_machine/version'

unless StateMachine::VERSION == '1.2.0'
  # If you see this message, please test removing this file
  # If it's still required, please bump up the version above
  Rails.logger.warn "Please remove me, StateMachine version has changed"
end

module StateMachine::Integrations::ActiveModel
  alias_method :around_validation_protected, :around_validation
  def around_validation(*args, &block)
    around_validation_protected(*args, &block)
  end
end
```

**Comment by seuros** [comment]
Why will you put this the initializer without checking manually that the version correct ?

**Comment by nthj** [comment]
It's more for when `state_machine` fixes the problem upstream, I'll get a notice in my logs to remove the monkeypatch.

**Comment by seuros** [comment]
I see :+1:

**Comment by MSch** [comment]
``` ruby
# Rails 4.1.0.rc1 and StateMachine don't play nice
# https://github.com/pluginaweek/state_machine/issues/295

require 'state_machine/version'

unless StateMachine::VERSION == '1.2.0'
  # If you see this message, please test removing this file
  # If it's still required, please bump up the version above
  Rails.logger.warn "Please remove me, StateMachine version has changed"
end

module StateMachine::Integrations::ActiveModel
  public :around_validation
end
```

works for me and is less hacky

**Comment by marclennox** [comment]
Yeah I have a fork of state machine I'm using until the author fixes it.  I'll send you later—

**Comment by marclennox** [comment]
Sorry ignore my last comment...  I'm using State Machine with 4.1rc1 using your recommend monkey patch and it's working great for me.

**Comment by nthj** [comment]
Nice, I did not know about `public :method_name`   

On March 8, 2014 at 10:18:18 AM CST, Marc Lennox notifications@github.com wrote:Sorry ignore my last comment... I'm using State Machine with 4.1rc1 using your recommend monkey patch and it's working great for me.  —Reply to this email directly or view it on GitHub.

**Comment by gucki** [comment]
Hm I wonder if this gem is still maintained? :-1:

**Comment by marclennox** [comment]
I've been wondering the same thing.  Would be a shame if not, this is a
really good gem and much better than the alternatives.

**Comment by fredngo** [comment]
Yes, I still prefer this gem to the Active Record enums in Rails 4.1.
+1 here, will use the hack until there is an update.

**Comment by saurabhnanda** [comment]
Just ran into this issue. Has this been fixed?

**Comment by charliemaffitt** [comment]
Not that I know of. I'm using the hack still.

**Comment by tanelsuurhans** [comment]
What's the holdup with this fix? Seems to be a rather straightforward issue,  no?

**Comment by charliemaffitt** [comment]
I doubt the gem is actively maintained, folks. This looks like abandonware to me.

**Comment by kovpack** [comment]
I've got the same problem. Now I think of removing it from my gem list, however, gem is cool. That is sad :(

**Comment by rusikf** [comment]
problem is stil exists, fork from  seuros  helped

**Comment by styledev** [comment]
It would be nice if the original developer would fix this one small issue...

**Comment by vickodin** [comment]
@MSch :+1:

**Comment by phlegx** [comment]
@MSch :+1:  super man...

**Comment by mikebaldry** [comment]
really this is still not fixed? Time for a new SM gem that is maintained?

**Comment by alienatix** [comment]
+1, please fix this issue.

**Comment by jaredbeck** [comment]
Thanks, @MSch.  That will tide my team over until we can switch to a fork or a different library.

**Comment by seuros** [comment]
@jaredbeck , you can use my fork. It has all fixes and many people are using it.

**Comment by jaredbeck** [comment]
> @jaredbeck , you can use my fork. It has all fixes and many people are using it.

Thanks, I'll check it out!

**Comment by fabioperrella** [comment]
+1

**Comment by the-teacher** [comment]
https://github.com/pluginaweek/state_machine/issues/251

**Comment by leckylao** [comment]
@MSch :+1:

**Comment by korun** [comment]
This problem is actual for Rails `4.1.1` too!

**Comment by gemtainers** [comment]
Have an idea about mainaining #331

**Comment by JohnSmall** [comment]
Mm, I've been using the forked version (seuros above) for sometime in 4.1.x and it's working fine. In 4.2 it fails utterly. I'm trying to look into now as I have a project to finish soon. But I think my work around will be to maintain state myself until I get a chance to dive into it.

**Comment by kernelzin** [comment]
Guys take a look 
https://github.com/gocardless/statesman

**Comment by davidcpell** [comment]
getting this problem on Rails 4.2, looks like @seuros' fork now works for that! thanks @seuros! any plans to take over maintenance of the gem?

**Comment by seuros** [comment]
@davidcpell : https://github.com/state-machines/state_machines-activerecord, there is just 1 small bug in 4.2. (initial state is not persisted, but can be worked around by either setting the default in the column or having a before_create callback)

**Comment by seuros** [comment]
@JohnSmall unless you are using Mongoid or another integrations, can you check if SM-AR works for you ?
