### ISSUE TITLE
state_machine_rspec

### ISSUE THREAD

**Issue by neumachen** [pluginaweek/state_machine#339]
So I want to contribute to that gem by adding a trigger_event function and was wondering if there's a built in way for gem for this?

Because right now, I can validate it to have events and what transitions it does but I want to make a test when triggering an even is allowed or not.

I know it sounds redundant when I have the have_events function already but requirement needs me to test for trigger events as well.

Thanks.

**Comment by seuros** [comment]
`#fire_event`

**Comment by neumachen** [comment]
Thanks.
