### ISSUE TITLE
state_event and record marshaling

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#39]
**qoobaa** opened this issue

There&rsquo;s a problem with using state_event and record serialization:

 @@@ ruby
class User < ActiveRecord::Base
  state_machine do
    event :verify do
      transition nil => :verified
    end

```
after_transition :on => :verify do |user|
  user.to_yaml
end
```

  end
end

User.create(:state_event => "verify")
# TypeError: can&rsquo;t dump anonymous class Class

 @@@

It&rsquo;s caused because to_yaml is serializing @state_event_transition instance variable (it contains Proc objects). The same problem exists when using Marshal.dump. I&rsquo;m using serialization to deliver e-mail messages in background.

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/29)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
Thanks for the report!  This is definitely verified as an issue and I&rsquo;ll work on putting a patch together over the next few days.

**Comment by obrie** [comment]
(from [2ddd583ac283c063e8e532337c6790ed117d7329]) Fix event transitions being kept around while running actions/callbacks, sometimes preventing object marshalling [#29 state:resolved]
http://github.com/pluginaweek/state_machine/commit/2ddd583ac283c063e8e532337c6790ed117d7329

**Comment by kule** [comment]
Just to add I'm having the same issue when using delayed_job - I can work around it just mentioning incase it's a recurrence that needs fixing...

``` ruby
class Subscriber < ActiveRecord::Base
  state_machine :initial => :subscribed do
    after_transition :on => :resubscribe, :do => :do_something
    event :subscribe do
      transition all => :subscribed
    end
    event :unsubscribe do
      transition :subscribed => :unsubscribed
    end
    event :resubscribe do
      transition :unsubscribed => :subscribed
    end
  end

  def do_something
  end
  handle_asynchronously :do_something
end
#....
subscriber.resubscribe # => can't dump anonymous module: Subscriber :state instance helpers

```

**Comment by mikepollitt** [comment]
I get the same issue. Here is the workaround I used:

https://gist.github.com/rwz/738734

**Comment by kule** [comment]
Hey @mikepollitt 

If you are having issues with DelayedJob - all you need to do remove handle_asynchronously and enqueue a worker instead e.g. using above example:

```
def do_something
  Delayed::Job.enqueue DoSomethingWorker.new(self.id)
end
```

Then add a worker:

```
class DoSomethingWorker < Struct.new(:subscriber_id)
  def perform
    subscriber = Subscriber.find(subscriber_id)
    # ...
  end
end
```
