### ISSUE TITLE
Missing i18n/internationalization  and/or documentation

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#43]
**Paul Strong** opened this issue

The state_machine README says that state_machine supports internationalization, but I cannot find any further explanation of how this works. After going through the API I cannot find anyway of doing internationalization of state names short of creating a i18n module from scratch.

Has this feature been implemented yet? I&rsquo;m sorry if I just overlooked something in the api or docs.

Any pointers or response would be greatly appreciated.

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/33)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
Paul,

I deeply apologize for not getting back to you earlier on this issue.  You&rsquo;ve pointed out a blatantly missing part of the ActiveRecord documentation :)  I&rsquo;ve since added better support for i18n and properly documented its usage: http://github.com/pluginaweek/state_machine/commit/e25a3207a629f11ee34c9bcbdd663751cd47e805

I realize you have probably found other ways to work around this in the meantime, but I hope that this helps going forward.

**Comment by ChristianPeters** [comment]
This is still an issue. I checked the README, the wiki, the API, found the `locale_path` method, started digging around, figuring out how the integration model works, read `/lib/state_machine/integrations/active_record/locale.rb`, guessed that there actually is some Rails i18n integration, googled for it and then landed here.

Please make that documentation easier to find.
