### ISSUE TITLE
before_create callbacks with state_machine transitions get called twice

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#67]
**Cory Forsyth** opened this issue

When there is an before_create callback on a model that calls a state_machine transition, that before_create callback gets triggered twice.

Here is an example gist, showing the problem occurring when using ActiveRecord and MongoMapper:
http://gist.github.com/501073

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/57)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
**Cory Forsyth** commented

gem versions:
state_machine 0.9.3
active_record 2.3.5
mongo_mapper 0.8.2

**Comment by obrie** [comment]
**Cory Forsyth** commented

here&rsquo;s a patch w/ a failing test for the ActiveRecord integration tests:

http://gist.github.com/501172

**Comment by obrie** [comment]
Hi Cory,

What you&rsquo;re seeing is actually just the behavior of those ORMs.  See the example below:

 @@@ ruby

class TestActiveRecord < ActiveRecord::Base
  before_create :do_a

  def do_a
    puts &rsquo;do_a: begin&rsquo;
    do_b
    puts &rsquo;do_a: end&rsquo;
  end

  def do_b
    if !state
      puts &rsquo;do_b: begin&rsquo;
      self.state = &rsquo;foo&rsquo;
      save
      puts &rsquo;do_b: end&rsquo;
    end
  end
end

TestActiveRecord.create

# => do_a: begin

# => do_b: begin

# => do_a: begin

# => do_a: end

# => do_b: end

# => do_a: end

 @@@

Notice that this doesn&rsquo;t involve state_machine.  In fact, if you were to take out the condition in the do_b method, this would result in an infinite loop (this will always occur if you call save from a before_save/create/update callback).

I would suggest rewriting your callbacks so that this behavior isn&rsquo;t encountered.

**Comment by apneadiving** [comment]
Just faced this behavior with 1.1.2 and mongoid 2.2.4, and rails 3.0.10.

My object is already created, I've the following state_machine:

```
field :status,              :type => String, :default => "in_creation"

state_machine :status, :initial => :in_creation do

  event :launch do
    transition :from => :in_creation, :to => :in_progress
  end

  before_transition :from => :in_creation, :to => :in_progress, :do => :on_launch

end

def on_launch
   binding.pry
end
```

I've `before_save` but they only change some values here and there.

When I trigger the event, I enter the `on_launch` method twice.

Any thought?

**Comment by obrie** [comment]
Hi @apneadiving -

I couldn't reproduce this issue.  I created an app and tested via the following:

Create app:

```
rvm 1.8.7
rvm gemset create sm67
rvm 1.8.7@sm67
gem install rails -v 3.0.10
rails new sm67 -O
```

Set Gemfile to:

```
source 'http://rubygems.org'

gem 'rails', '3.0.10'

gem 'mongoid', '2.2.4'
gem 'state_machine', '1.1.2'
```

Set up config:

```
bundle install
rails g mongoid:config
```

Add app/models/vehicle.rb:

``` ruby
class Vehicle
  include Mongoid::Document

  field :status, :type => String, :default => "in_creation"

  state_machine :status, :initial => :in_creation do
    event :launch do
      transition :from => :in_creation, :to => :in_progress
    end

    before_transition :from => :in_creation, :to => :in_progress, :do => :on_launch
  end

  def on_launch
    puts "on launch"
  end
end
```

Test:

``` ruby
1.8.7-p352 :001 > v = Vehicle.new
 => #<Vehicle _id: 4f36e1bcb876bb1cff000001, _type: nil, status: "in_creation"> 
1.8.7-p352 :002 > v.save
 => true 
1.8.7-p352 :003 > v
 => #<Vehicle _id: 4f36e1bcb876bb1cff000001, _type: nil, status: "in_creation"> 
1.8.7-p352 :004 > v = Vehicle.first
 => #<Vehicle _id: 4f36e1bcb876bb1cff000001, _type: nil, status: "in_creation"> 
1.8.7-p352 :005 > vehicle.launch
on launch
 => true
```

As you can see, `on_launch` only appears to get run once.  Are you positive that there isn't anything else in the model that could be triggering this?  Could you try simplifying the model a bit or providing access to an example where the error is occurring?

Thanks.

**Comment by apneadiving** [comment]
@obrie Thank you VERY much for digging this.

I work on legacy code and maybe missed some part of it.

Because I had to go forward, I kept the state machine for state handling but replaced transitions with around filters.

I won't be able to recheck this then, so consider my report invalid.

Thanks again ;)

**Comment by apneadiving** [comment]
@obrie : seems I finally found the origin of the issue: Spork, somehow.

If you want to know more, we are discussing with mongoid maintainers here: https://github.com/mongoid/mongoid/issues/1752

**Comment by bsa7** [comment]
When i add observer for models:
```ruby
User
User::Regular
User::Admin
```
then
```ruby
user = User::Regular.new
user.activate
```
and `after_transition` callback for `User::Regular` was called twice.
When i remove the `User` from observable models - callback become to once calling per event.
