### ISSUE TITLE
State event translation missing

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#77]
**Morgan Christiansson** opened this issue

I get the following validation error:
    ActiveRecord::RecordInvalid: Validation failed: State event translation missing: en, activerecord, errors, models, my_model, attributes, state_event, invalid_event

So the default message isn&rsquo;t loading..

This is what I was expecting:
    StateMachine::InvalidTransition: Cannot transition state via :acknowledge from :resolved

This behaviour was introduced by [this commit in event_collection.rb](https://github.com/pluginaweek/state_machine/commit/d4ae362fa27bc4d3f568de763912b1eb0ba294c4#L4L109)

Where

```
machine.invalidate(object, :state, :invalid_transition, [[:event, name]])
```

was changed to

```
machine.invalidate(object, :state, :invalid_transition, [[:event, human_name(object.class)]])
```

Thanks for a great gem! :-)

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/67)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
**Morgan Christiansson** commented

It&rsquo;s strange though. I thought adding the following in test/unit/integrations/active_record_test.rb

```
record = @model.new(:state => &rsquo;idling&rsquo;)

machine.invalidate(record, :event, :invalid_event, [[:state, machine.states.match!(record).human_name(record.class)]])
assert_equal [&rsquo;State cannot transition when ignite&rsquo;], record.errors.full_messages
```

would reproduce it. But it does not.

Running Rails 2.3.10

**Comment by obrie** [comment]
Hey Morgan -

My only possible explanation there is that perhaps there is another library you&rsquo;re using that is modifying I18n.load_path in an unexpected manner.  Even when I18n.reload! is called, all of the necessary files for state_machine should be in the load_path and get used.  I&rsquo;ve been unable to reproduce this locally.

If you can provide a reproducible test case in state_machine, please feel free to reopen this bug.

**Comment by obrie** [comment]
Re-opening as I was able to reproduce this in the test environment.

**Comment by obrie** [comment]
(from [105c9039f8be713dfbf52c62df3f839f4d439ee6]) Fix translations not being available under certain environments in Rails applications [#67 state:resolved]
https://github.com/pluginaweek/state_machine/commit/105c9039f8be713dfbf52c62df3f839f4d439ee6

**Comment by obrie** [comment]
**Morgan Christiansson** commented

Hi Aaron, using your advice on I18n I added I18n.reload! to our test and spec_helpers and the validation messages started working.

If you managed to fix it so it works without it that&rsquo;s great!

Thanks,
Morgan

**Comment by hishma** [comment]
Hello,

I’m getting this error using 1.1.2 in a brand new rails 3.2.3 app and ruby 1.9.3-p194.

Looking at Rails.configuration.i18n.load_path, these 2 files are actually the first ones in the list:

../gems/state_machine-1.1.2/lib/state_machine/integrations/active_record/locale.rb
../gems/state_machine-1.1.2/lib/state_machine/integrations/active_model/locale.rb

**Comment by obrie** [comment]
Hey @hishma -

Any chance you can share a project which is having this issue on GitHub so that I can try to reproduce it locally?

Thanks!
