### ISSUE TITLE
Rails 3.1.rc4 Cant transition

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#95]
**magpieuk** opened this issue

I have tried adding the gem to a project I am working on and could not get it to work.

adding the following to a basic class works

```
state_machine :status, :initial => :active, :namespace => &rsquo;alarm&rsquo; do
  event(:enable) { transition all => :active }
  event(:disable) { transition all => :off }

  state :active, :value => 1
  state :off, :value => 0
end
```

However when it is added into a model the transitions fail

v.disable_alarm 
StateMachine::InvalidTransition: Cannot transition status via :disable from :active

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/85)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
**magpieuk** commented

I think further investigation by me is required. The tests all run without problem against activerecord and activemodel 3.1.rc.4

**Comment by obrie** [comment]
**magpieuk** commented

Think I have got to the bottom of this, when the object is initialized the initial state is not being set with Activerecord. This was then not allowing the action changes to occur as the record was invalid. The error messages are also not being pulled through so it is being reported as:

ActiveRecord::RecordInvalid: Validation failed: Status translation missing: en.activerecord.errors.models.opportunity.attributes.status.invalid

At the moment I have got round the issue by using:

  after_initialize :set_initial_state

  def set_initial_state
    self.state ||= "enquiry"
  end

Hopefully I will be able to find out why this is happening and get back to you

**Comment by obrie** [comment]
Thanks for taking the time to report this issue and look into it!

In the first example (the "status" state machine), do you also have the same issue where when you initialize the record, the "status" is set to nil?  If that&rsquo;s the case, is there any chance you could try to reproduce the same setup on a vanilla Rails project?  What I&rsquo;d like to see is whether there&rsquo;s another library in your Rails project that could potentially be conflicting with state_machine.  If we can narrow that down, that will really help identify if there&rsquo;s a workaround I can put in or if the conflicting library needs to change.

If it can be reproduced in a vanilla Rails project, then I&rsquo;d love to grab a copy of that so that I can further debug.  Would love to get this resolved for you so that you can avoid putting in the after_initialize workaround!

**Comment by obrie** [comment]
**magpieuk** commented

Hi Aaron, back from holiday, will see what I can find out for you.

**Comment by obrie** [comment]
**Alex Tan** commented

magpieuk, have you checked to see if you have any before_save or other callbacks that are returning a nil or false value? I found your ticket because I was having the same issue, and having my before_saves return true solved the issue.

**Comment by obrie** [comment]
**Alex Tan** commented

**Comment by obrie** [comment]
Any further update here?  For now, I&rsquo;m going to mark this as resolved.  However, please feel welcome to re-open if you are able to find additional information about why the state isn&rsquo;t getting initialized.

**Comment by BellandWhistle** [comment]
I had this problem, but that was because i use set an event called `validate`
