### ISSUE TITLE
after_transition, before_transition callback never called with Rails 3

### ISSUE THREAD

**Issue by obrie** [pluginaweek/state_machine#96]
**MMore** opened this issue

I am using state_machine 1.0.1 with Rails 3.0.9 and ActiveRecord.

Nearly everything works but callbacks like after_transition or before_transition. They are never called. Bizzarely it works with rails console, not with the rails app started with "rails server".

Can you reproduce it?

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13288/tickets/86)

 This ticket has 0 attachment(s).

**Comment by obrie** [comment]
Hi MMore,

Thanks for the report!  Unfortunately I&rsquo;ve been unable to reproduce this issue.  If you can provide a project that I can access demonstrating the issue, I&rsquo;d love to take a look at it.  Feel free to re-open if you&rsquo;re able to provide a reproducible test case.

Hope we can resolve the issue if you haven&rsquo;t been able to already!

**Comment by chabgood** [comment]
I am seeing the same thing here, I have a Rails.logger.info Statement in the after_transition block but it never gets there.  I also cannot seem to get the observer to work either.

**Comment by obrie** [comment]
Hey @chabgood -

I had one other report that observers weren't working, but I believe this got fixed by the latest unreleased version.  Can you try out the latest and see if this solves any of your issues?  As far as the `after_transition` block, I can't say that I've seen this myself -- is there any way you can providing a reproducible example (posted on github or otherwise) that I can use to figure out the issue.

Thanks!

**Comment by alex-tan** [comment]
I'm having similar issues, specifically with targeted attributes. For example:

[The model](https://gist.github.com/2915822)
[The spec](https://gist.github.com/2915829)

This is running state_machine 1.1.2, Rails 3.2.3 and rspec-rails 2.10.1

**Comment by obrie** [comment]
@alex-tan -

Transition callbacks only apply to the machine they were defined in.  In your case, you're running an event on the `public_state` machine, but the `before_transition` callback is defined in the `state` machine.  There's currently no feature that allows callbacks to be shared across machines.

**Comment by alex-tan** [comment]
@obrie -

I probably should have read the documentation closer. Good to know :)
